const std = @import("std");

// PKCS#11 v3.1 Zig bindings
// Based on the OASIS PKCS#11 Specification Version 3.1

// Base types.
// On UNIX, CK_ULONG is `unsigned long int` which is pointer-sized.
pub const CK_ULONG = usize;
pub const CK_LONG = isize;
pub const CK_BYTE = u8;
pub const CK_CHAR = CK_BYTE;
pub const CK_UTF8CHAR = CK_BYTE;
pub const CK_BBOOL = CK_BYTE;
pub const CK_FLAGS = CK_ULONG;
pub const CK_VOID_PTR = ?*anyopaque;
pub const CK_BYTE_PTR = ?[*]CK_BYTE;
pub const CK_ULONG_PTR = ?*CK_ULONG;
pub const CK_UTF8CHAR_PTR = ?[*]CK_UTF8CHAR;

pub const CK_TRUE: CK_BBOOL = 1;
pub const CK_FALSE: CK_BBOOL = 0;

// Handles and IDs.
pub const CK_SLOT_ID = CK_ULONG;
pub const CK_SESSION_HANDLE = CK_ULONG;
pub const CK_OBJECT_HANDLE = CK_ULONG;
pub const CK_NOTIFICATION = CK_ULONG;
pub const CK_MECHANISM_TYPE = CK_ULONG;
pub const CK_ATTRIBUTE_TYPE = CK_ULONG;
pub const CK_USER_TYPE = CK_ULONG;

pub const CK_OBJECT_CLASS = CK_ULONG;
pub const CK_KEY_TYPE = CK_ULONG;
pub const CK_CERTIFICATE_TYPE = CK_ULONG;
pub const CK_STATE = CK_ULONG;
pub const CK_HW_FEATURE_TYPE = CK_ULONG;

pub const CK_INVALID_HANDLE: CK_ULONG = 0;
pub const CK_UNAVAILABLE_INFORMATION: CK_ULONG = ~@as(CK_ULONG, 0);
pub const CK_EFFECTIVELY_INFINITE: CK_ULONG = 0;

// Object classes.
pub const CKO_DATA: CK_OBJECT_CLASS = 0x00000000;
pub const CKO_CERTIFICATE: CK_OBJECT_CLASS = 0x00000001;
pub const CKO_PUBLIC_KEY: CK_OBJECT_CLASS = 0x00000002;
pub const CKO_PRIVATE_KEY: CK_OBJECT_CLASS = 0x00000003;
pub const CKO_SECRET_KEY: CK_OBJECT_CLASS = 0x00000004;
pub const CKO_HW_FEATURE: CK_OBJECT_CLASS = 0x00000005;
pub const CKO_DOMAIN_PARAMETERS: CK_OBJECT_CLASS = 0x00000006;
pub const CKO_MECHANISM: CK_OBJECT_CLASS = 0x00000007;
pub const CKO_OTP_KEY: CK_OBJECT_CLASS = 0x00000008;
pub const CKO_PROFILE: CK_OBJECT_CLASS = 0x00000009;
pub const CKO_VENDOR_DEFINED: CK_OBJECT_CLASS = 0x80000000;

// Key types.
pub const CKK_RSA: CK_KEY_TYPE = 0x00000000;
pub const CKK_DSA: CK_KEY_TYPE = 0x00000001;
pub const CKK_DH: CK_KEY_TYPE = 0x00000002;
pub const CKK_EC: CK_KEY_TYPE = 0x00000003;
pub const CKK_X9_42_DH: CK_KEY_TYPE = 0x00000004;
pub const CKK_KEA: CK_KEY_TYPE = 0x00000005;
pub const CKK_GENERIC_SECRET: CK_KEY_TYPE = 0x00000010;
pub const CKK_RC2: CK_KEY_TYPE = 0x00000011;
pub const CKK_RC4: CK_KEY_TYPE = 0x00000012;
pub const CKK_DES: CK_KEY_TYPE = 0x00000013;
pub const CKK_DES2: CK_KEY_TYPE = 0x00000014;
pub const CKK_DES3: CK_KEY_TYPE = 0x00000015;
pub const CKK_CAST: CK_KEY_TYPE = 0x00000016;
pub const CKK_CAST3: CK_KEY_TYPE = 0x00000017;
pub const CKK_CAST128: CK_KEY_TYPE = 0x00000018;
pub const CKK_RC5: CK_KEY_TYPE = 0x00000019;
pub const CKK_IDEA: CK_KEY_TYPE = 0x0000001A;
pub const CKK_SKIPJACK: CK_KEY_TYPE = 0x0000001B;
pub const CKK_BATON: CK_KEY_TYPE = 0x0000001C;
pub const CKK_JUNIPER: CK_KEY_TYPE = 0x0000001D;
pub const CKK_CDMF: CK_KEY_TYPE = 0x0000001E;
pub const CKK_AES: CK_KEY_TYPE = 0x0000001F;
pub const CKK_BLOWFISH: CK_KEY_TYPE = 0x00000020;
pub const CKK_TWOFISH: CK_KEY_TYPE = 0x00000021;
pub const CKK_SECURID: CK_KEY_TYPE = 0x00000022;
pub const CKK_HOTP: CK_KEY_TYPE = 0x00000023;
pub const CKK_ACTI: CK_KEY_TYPE = 0x00000024;
pub const CKK_CAMELLIA: CK_KEY_TYPE = 0x00000025;
pub const CKK_ARIA: CK_KEY_TYPE = 0x00000026;
pub const CKK_MD5_HMAC: CK_KEY_TYPE = 0x00000027;
pub const CKK_SHA_1_HMAC: CK_KEY_TYPE = 0x00000028;
pub const CKK_RIPEMD128_HMAC: CK_KEY_TYPE = 0x00000029;
pub const CKK_RIPEMD160_HMAC: CK_KEY_TYPE = 0x0000002A;
pub const CKK_SHA256_HMAC: CK_KEY_TYPE = 0x0000002B;
pub const CKK_SHA384_HMAC: CK_KEY_TYPE = 0x0000002C;
pub const CKK_SHA512_HMAC: CK_KEY_TYPE = 0x0000002D;
pub const CKK_SHA224_HMAC: CK_KEY_TYPE = 0x0000002E;
pub const CKK_SEED: CK_KEY_TYPE = 0x0000002F;
pub const CKK_GOSTR3410: CK_KEY_TYPE = 0x00000030;
pub const CKK_GOSTR3411: CK_KEY_TYPE = 0x00000031;
pub const CKK_GOST28147: CK_KEY_TYPE = 0x00000032;
pub const CKK_CHACHA20: CK_KEY_TYPE = 0x00000033;
pub const CKK_POLY1305: CK_KEY_TYPE = 0x00000034;
pub const CKK_AES_XTS: CK_KEY_TYPE = 0x00000035;
pub const CKK_SHA3_224_HMAC: CK_KEY_TYPE = 0x00000036;
pub const CKK_SHA3_256_HMAC: CK_KEY_TYPE = 0x00000037;
pub const CKK_SHA3_384_HMAC: CK_KEY_TYPE = 0x00000038;
pub const CKK_SHA3_512_HMAC: CK_KEY_TYPE = 0x00000039;
pub const CKK_BLAKE2B_160_HMAC: CK_KEY_TYPE = 0x0000003A;
pub const CKK_BLAKE2B_256_HMAC: CK_KEY_TYPE = 0x0000003B;
pub const CKK_BLAKE2B_384_HMAC: CK_KEY_TYPE = 0x0000003C;
pub const CKK_BLAKE2B_512_HMAC: CK_KEY_TYPE = 0x0000003D;
pub const CKK_SALSA20: CK_KEY_TYPE = 0x0000003E;
pub const CKK_X2RATCHET: CK_KEY_TYPE = 0x0000003F;
pub const CKK_EC_EDWARDS: CK_KEY_TYPE = 0x00000040;
pub const CKK_EC_MONTGOMERY: CK_KEY_TYPE = 0x00000041;
pub const CKK_HKDF: CK_KEY_TYPE = 0x00000042;
pub const CKK_SHA512_224_HMAC: CK_KEY_TYPE = 0x00000043;
pub const CKK_SHA512_256_HMAC: CK_KEY_TYPE = 0x00000044;
pub const CKK_SHA512_T_HMAC: CK_KEY_TYPE = 0x00000045;
pub const CKK_HSS: CK_KEY_TYPE = 0x00000046;
pub const CKK_VENDOR_DEFINED: CK_KEY_TYPE = 0x80000000;

// Certificate types.
pub const CKC_X_509: CK_CERTIFICATE_TYPE = 0x00000000;
pub const CKC_X_509_ATTR_CERT: CK_CERTIFICATE_TYPE = 0x00000001;
pub const CKC_WTLS: CK_CERTIFICATE_TYPE = 0x00000002;
pub const CKC_VENDOR_DEFINED: CK_CERTIFICATE_TYPE = 0x80000000;

// Session states.
pub const CKS_RO_PUBLIC_SESSION: CK_STATE = 0;
pub const CKS_RO_USER_FUNCTIONS: CK_STATE = 1;
pub const CKS_RW_PUBLIC_SESSION: CK_STATE = 2;
pub const CKS_RW_USER_FUNCTIONS: CK_STATE = 3;
pub const CKS_RW_SO_FUNCTIONS: CK_STATE = 4;

// User types.
pub const CKU_SO: CK_USER_TYPE = 0;
pub const CKU_USER: CK_USER_TYPE = 1;
pub const CKU_CONTEXT_SPECIFIC: CK_USER_TYPE = 2;

// Attribute types.
pub const CKA_CLASS: CK_ATTRIBUTE_TYPE = 0x00000000;
pub const CKA_TOKEN: CK_ATTRIBUTE_TYPE = 0x00000001;
pub const CKA_PRIVATE: CK_ATTRIBUTE_TYPE = 0x00000002;
pub const CKA_LABEL: CK_ATTRIBUTE_TYPE = 0x00000003;
pub const CKA_UNIQUE_ID: CK_ATTRIBUTE_TYPE = 0x00000004;
pub const CKA_APPLICATION: CK_ATTRIBUTE_TYPE = 0x00000010;
pub const CKA_VALUE: CK_ATTRIBUTE_TYPE = 0x00000011;
pub const CKA_OBJECT_ID: CK_ATTRIBUTE_TYPE = 0x00000012;
pub const CKA_CERTIFICATE_TYPE: CK_ATTRIBUTE_TYPE = 0x00000080;
pub const CKA_ISSUER: CK_ATTRIBUTE_TYPE = 0x00000081;
pub const CKA_SERIAL_NUMBER: CK_ATTRIBUTE_TYPE = 0x00000082;
pub const CKA_AC_ISSUER: CK_ATTRIBUTE_TYPE = 0x00000083;
pub const CKA_OWNER: CK_ATTRIBUTE_TYPE = 0x00000084;
pub const CKA_ATTR_TYPES: CK_ATTRIBUTE_TYPE = 0x00000085;
pub const CKA_TRUSTED: CK_ATTRIBUTE_TYPE = 0x00000086;
pub const CKA_CERTIFICATE_CATEGORY: CK_ATTRIBUTE_TYPE = 0x00000087;
pub const CKA_JAVA_MIDP_SECURITY_DOMAIN: CK_ATTRIBUTE_TYPE = 0x00000088;
pub const CKA_URL: CK_ATTRIBUTE_TYPE = 0x00000089;
pub const CKA_HASH_OF_SUBJECT_PUBLIC_KEY: CK_ATTRIBUTE_TYPE = 0x0000008A;
pub const CKA_HASH_OF_ISSUER_PUBLIC_KEY: CK_ATTRIBUTE_TYPE = 0x0000008B;
pub const CKA_NAME_HASH_ALGORITHM: CK_ATTRIBUTE_TYPE = 0x0000008C;
pub const CKA_CHECK_VALUE: CK_ATTRIBUTE_TYPE = 0x00000090;
pub const CKA_KEY_TYPE: CK_ATTRIBUTE_TYPE = 0x00000100;
pub const CKA_SUBJECT: CK_ATTRIBUTE_TYPE = 0x00000101;
pub const CKA_ID: CK_ATTRIBUTE_TYPE = 0x00000102;
pub const CKA_SENSITIVE: CK_ATTRIBUTE_TYPE = 0x00000103;
pub const CKA_ENCRYPT: CK_ATTRIBUTE_TYPE = 0x00000104;
pub const CKA_DECRYPT: CK_ATTRIBUTE_TYPE = 0x00000105;
pub const CKA_WRAP: CK_ATTRIBUTE_TYPE = 0x00000106;
pub const CKA_UNWRAP: CK_ATTRIBUTE_TYPE = 0x00000107;
pub const CKA_SIGN: CK_ATTRIBUTE_TYPE = 0x00000108;
pub const CKA_SIGN_RECOVER: CK_ATTRIBUTE_TYPE = 0x00000109;
pub const CKA_VERIFY: CK_ATTRIBUTE_TYPE = 0x0000010A;
pub const CKA_VERIFY_RECOVER: CK_ATTRIBUTE_TYPE = 0x0000010B;
pub const CKA_DERIVE: CK_ATTRIBUTE_TYPE = 0x0000010C;
pub const CKA_START_DATE: CK_ATTRIBUTE_TYPE = 0x00000110;
pub const CKA_END_DATE: CK_ATTRIBUTE_TYPE = 0x00000111;
pub const CKA_MODULUS: CK_ATTRIBUTE_TYPE = 0x00000120;
pub const CKA_MODULUS_BITS: CK_ATTRIBUTE_TYPE = 0x00000121;
pub const CKA_PUBLIC_EXPONENT: CK_ATTRIBUTE_TYPE = 0x00000122;
pub const CKA_PRIVATE_EXPONENT: CK_ATTRIBUTE_TYPE = 0x00000123;
pub const CKA_PRIME_1: CK_ATTRIBUTE_TYPE = 0x00000124;
pub const CKA_PRIME_2: CK_ATTRIBUTE_TYPE = 0x00000125;
pub const CKA_EXPONENT_1: CK_ATTRIBUTE_TYPE = 0x00000126;
pub const CKA_EXPONENT_2: CK_ATTRIBUTE_TYPE = 0x00000127;
pub const CKA_COEFFICIENT: CK_ATTRIBUTE_TYPE = 0x00000128;
pub const CKA_PUBLIC_KEY_INFO: CK_ATTRIBUTE_TYPE = 0x00000129;
pub const CKA_PRIME: CK_ATTRIBUTE_TYPE = 0x00000130;
pub const CKA_SUBPRIME: CK_ATTRIBUTE_TYPE = 0x00000131;
pub const CKA_BASE: CK_ATTRIBUTE_TYPE = 0x00000132;
pub const CKA_PRIME_BITS: CK_ATTRIBUTE_TYPE = 0x00000133;
pub const CKA_SUBPRIME_BITS: CK_ATTRIBUTE_TYPE = 0x00000134;
pub const CKA_VALUE_BITS: CK_ATTRIBUTE_TYPE = 0x00000160;
pub const CKA_VALUE_LEN: CK_ATTRIBUTE_TYPE = 0x00000161;
pub const CKA_EXTRACTABLE: CK_ATTRIBUTE_TYPE = 0x00000162;
pub const CKA_LOCAL: CK_ATTRIBUTE_TYPE = 0x00000163;
pub const CKA_NEVER_EXTRACTABLE: CK_ATTRIBUTE_TYPE = 0x00000164;
pub const CKA_ALWAYS_SENSITIVE: CK_ATTRIBUTE_TYPE = 0x00000165;
pub const CKA_KEY_GEN_MECHANISM: CK_ATTRIBUTE_TYPE = 0x00000166;
pub const CKA_MODIFIABLE: CK_ATTRIBUTE_TYPE = 0x00000170;
pub const CKA_COPYABLE: CK_ATTRIBUTE_TYPE = 0x00000171;
pub const CKA_DESTROYABLE: CK_ATTRIBUTE_TYPE = 0x00000172;
pub const CKA_EC_PARAMS: CK_ATTRIBUTE_TYPE = 0x00000180;
pub const CKA_EC_POINT: CK_ATTRIBUTE_TYPE = 0x00000181;
pub const CKA_ALWAYS_AUTHENTICATE: CK_ATTRIBUTE_TYPE = 0x00000202;
pub const CKA_WRAP_WITH_TRUSTED: CK_ATTRIBUTE_TYPE = 0x00000210;
pub const CKF_ARRAY_ATTRIBUTE: CK_FLAGS = 0x40000000;
pub const CKA_WRAP_TEMPLATE: CK_ATTRIBUTE_TYPE = CKF_ARRAY_ATTRIBUTE | 0x00000211;
pub const CKA_UNWRAP_TEMPLATE: CK_ATTRIBUTE_TYPE = CKF_ARRAY_ATTRIBUTE | 0x00000212;
pub const CKA_DERIVE_TEMPLATE: CK_ATTRIBUTE_TYPE = CKF_ARRAY_ATTRIBUTE | 0x00000213;
pub const CKA_OTP_FORMAT: CK_ATTRIBUTE_TYPE = 0x00000220;
pub const CKA_OTP_LENGTH: CK_ATTRIBUTE_TYPE = 0x00000221;
pub const CKA_OTP_TIME_INTERVAL: CK_ATTRIBUTE_TYPE = 0x00000222;
pub const CKA_OTP_USER_FRIENDLY_MODE: CK_ATTRIBUTE_TYPE = 0x00000223;
pub const CKA_OTP_CHALLENGE_REQUIREMENT: CK_ATTRIBUTE_TYPE = 0x00000224;
pub const CKA_OTP_TIME_REQUIREMENT: CK_ATTRIBUTE_TYPE = 0x00000225;
pub const CKA_OTP_COUNTER_REQUIREMENT: CK_ATTRIBUTE_TYPE = 0x00000226;
pub const CKA_OTP_PIN_REQUIREMENT: CK_ATTRIBUTE_TYPE = 0x00000227;
pub const CKA_OTP_COUNTER: CK_ATTRIBUTE_TYPE = 0x0000022E;
pub const CKA_OTP_TIME: CK_ATTRIBUTE_TYPE = 0x0000022F;
pub const CKA_OTP_USER_IDENTIFIER: CK_ATTRIBUTE_TYPE = 0x0000022A;
pub const CKA_OTP_SERVICE_IDENTIFIER: CK_ATTRIBUTE_TYPE = 0x0000022B;
pub const CKA_OTP_SERVICE_LOGO: CK_ATTRIBUTE_TYPE = 0x0000022C;
pub const CKA_OTP_SERVICE_LOGO_TYPE: CK_ATTRIBUTE_TYPE = 0x0000022D;
pub const CKA_GOSTR3410_PARAMS: CK_ATTRIBUTE_TYPE = 0x00000250;
pub const CKA_GOSTR3411_PARAMS: CK_ATTRIBUTE_TYPE = 0x00000251;
pub const CKA_GOST28147_PARAMS: CK_ATTRIBUTE_TYPE = 0x00000252;
pub const CKA_HW_FEATURE_TYPE: CK_ATTRIBUTE_TYPE = 0x00000300;
pub const CKA_RESET_ON_INIT: CK_ATTRIBUTE_TYPE = 0x00000301;
pub const CKA_HAS_RESET: CK_ATTRIBUTE_TYPE = 0x00000302;
pub const CKA_PIXEL_X: CK_ATTRIBUTE_TYPE = 0x00000400;
pub const CKA_PIXEL_Y: CK_ATTRIBUTE_TYPE = 0x00000401;
pub const CKA_RESOLUTION: CK_ATTRIBUTE_TYPE = 0x00000402;
pub const CKA_CHAR_ROWS: CK_ATTRIBUTE_TYPE = 0x00000403;
pub const CKA_CHAR_COLUMNS: CK_ATTRIBUTE_TYPE = 0x00000404;
pub const CKA_COLOR: CK_ATTRIBUTE_TYPE = 0x00000405;
pub const CKA_BITS_PER_PIXEL: CK_ATTRIBUTE_TYPE = 0x00000406;
pub const CKA_CHAR_SETS: CK_ATTRIBUTE_TYPE = 0x00000480;
pub const CKA_ENCODING_METHODS: CK_ATTRIBUTE_TYPE = 0x00000481;
pub const CKA_MIME_TYPES: CK_ATTRIBUTE_TYPE = 0x00000482;
pub const CKA_MECHANISM_TYPE: CK_ATTRIBUTE_TYPE = 0x00000500;
pub const CKA_REQUIRED_CMS_ATTRIBUTES: CK_ATTRIBUTE_TYPE = 0x00000501;
pub const CKA_DEFAULT_CMS_ATTRIBUTES: CK_ATTRIBUTE_TYPE = 0x00000502;
pub const CKA_SUPPORTED_CMS_ATTRIBUTES: CK_ATTRIBUTE_TYPE = 0x00000503;
pub const CKA_ALLOWED_MECHANISMS: CK_ATTRIBUTE_TYPE = CKF_ARRAY_ATTRIBUTE | 0x00000600;
pub const CKA_PROFILE_ID: CK_ATTRIBUTE_TYPE = 0x00000601;
pub const CKA_X2RATCHET_BAG: CK_ATTRIBUTE_TYPE = 0x00000602;
pub const CKA_X2RATCHET_BAGSIZE: CK_ATTRIBUTE_TYPE = 0x00000603;
pub const CKA_X2RATCHET_BOBS1STMSG: CK_ATTRIBUTE_TYPE = 0x00000604;
pub const CKA_X2RATCHET_CKR: CK_ATTRIBUTE_TYPE = 0x00000605;
pub const CKA_X2RATCHET_CKS: CK_ATTRIBUTE_TYPE = 0x00000606;
pub const CKA_X2RATCHET_DHP: CK_ATTRIBUTE_TYPE = 0x00000607;
pub const CKA_X2RATCHET_DHR: CK_ATTRIBUTE_TYPE = 0x00000608;
pub const CKA_X2RATCHET_DHS: CK_ATTRIBUTE_TYPE = 0x00000609;
pub const CKA_X2RATCHET_HKR: CK_ATTRIBUTE_TYPE = 0x0000060A;
pub const CKA_X2RATCHET_HKS: CK_ATTRIBUTE_TYPE = 0x0000060B;
pub const CKA_X2RATCHET_ISALICE: CK_ATTRIBUTE_TYPE = 0x0000060C;
pub const CKA_X2RATCHET_NHKR: CK_ATTRIBUTE_TYPE = 0x0000060D;
pub const CKA_X2RATCHET_NHKS: CK_ATTRIBUTE_TYPE = 0x0000060E;
pub const CKA_X2RATCHET_NR: CK_ATTRIBUTE_TYPE = 0x0000060F;
pub const CKA_X2RATCHET_NS: CK_ATTRIBUTE_TYPE = 0x00000610;
pub const CKA_X2RATCHET_PNS: CK_ATTRIBUTE_TYPE = 0x00000611;
pub const CKA_X2RATCHET_RK: CK_ATTRIBUTE_TYPE = 0x00000612;
pub const CKA_HSS_LEVELS: CK_ATTRIBUTE_TYPE = 0x00000617;
pub const CKA_HSS_LMS_TYPE: CK_ATTRIBUTE_TYPE = 0x00000618;
pub const CKA_HSS_LMOTS_TYPE: CK_ATTRIBUTE_TYPE = 0x00000619;
pub const CKA_HSS_LMS_TYPES: CK_ATTRIBUTE_TYPE = 0x0000061A;
pub const CKA_HSS_LMOTS_TYPES: CK_ATTRIBUTE_TYPE = 0x0000061B;
pub const CKA_HSS_KEYS_REMAINING: CK_ATTRIBUTE_TYPE = 0x0000061C;
pub const CKA_VENDOR_DEFINED: CK_ATTRIBUTE_TYPE = 0x80000000;

// Mechanism types.
pub const CKM_RSA_PKCS_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00000000;
pub const CKM_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000001;
pub const CKM_RSA_9796: CK_MECHANISM_TYPE = 0x00000002;
pub const CKM_RSA_X_509: CK_MECHANISM_TYPE = 0x00000003;
pub const CKM_MD2_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000004;
pub const CKM_MD5_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000005;
pub const CKM_SHA1_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000006;
pub const CKM_RIPEMD128_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000007;
pub const CKM_RIPEMD160_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000008;
pub const CKM_RSA_PKCS_OAEP: CK_MECHANISM_TYPE = 0x00000009;
pub const CKM_RSA_X9_31_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x0000000A;
pub const CKM_RSA_X9_31: CK_MECHANISM_TYPE = 0x0000000B;
pub const CKM_SHA1_RSA_X9_31: CK_MECHANISM_TYPE = 0x0000000C;
pub const CKM_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x0000000D;
pub const CKM_SHA1_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x0000000E;
pub const CKM_DSA_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00000010;
pub const CKM_DSA: CK_MECHANISM_TYPE = 0x00000011;
pub const CKM_DSA_SHA1: CK_MECHANISM_TYPE = 0x00000012;
pub const CKM_DSA_SHA224: CK_MECHANISM_TYPE = 0x00000013;
pub const CKM_DSA_SHA256: CK_MECHANISM_TYPE = 0x00000014;
pub const CKM_DSA_SHA384: CK_MECHANISM_TYPE = 0x00000015;
pub const CKM_DSA_SHA512: CK_MECHANISM_TYPE = 0x00000016;
pub const CKM_DSA_SHA3_224: CK_MECHANISM_TYPE = 0x00000018;
pub const CKM_DSA_SHA3_256: CK_MECHANISM_TYPE = 0x00000019;
pub const CKM_DSA_SHA3_384: CK_MECHANISM_TYPE = 0x0000001A;
pub const CKM_DSA_SHA3_512: CK_MECHANISM_TYPE = 0x0000001B;
pub const CKM_DH_PKCS_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00000020;
pub const CKM_DH_PKCS_DERIVE: CK_MECHANISM_TYPE = 0x00000021;
pub const CKM_X9_42_DH_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00000030;
pub const CKM_X9_42_DH_DERIVE: CK_MECHANISM_TYPE = 0x00000031;
pub const CKM_X9_42_DH_HYBRID_DERIVE: CK_MECHANISM_TYPE = 0x00000032;
pub const CKM_X9_42_MQV_DERIVE: CK_MECHANISM_TYPE = 0x00000033;
pub const CKM_SHA256_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000040;
pub const CKM_SHA384_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000041;
pub const CKM_SHA512_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000042;
pub const CKM_SHA256_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000043;
pub const CKM_SHA384_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000044;
pub const CKM_SHA512_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000045;
pub const CKM_SHA224_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000046;
pub const CKM_SHA224_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000047;
pub const CKM_SHA512_224: CK_MECHANISM_TYPE = 0x00000048;
pub const CKM_SHA512_224_HMAC: CK_MECHANISM_TYPE = 0x00000049;
pub const CKM_SHA512_224_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x0000004A;
pub const CKM_SHA512_224_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x0000004B;
pub const CKM_SHA512_256: CK_MECHANISM_TYPE = 0x0000004C;
pub const CKM_SHA512_256_HMAC: CK_MECHANISM_TYPE = 0x0000004D;
pub const CKM_SHA512_256_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x0000004E;
pub const CKM_SHA512_256_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x0000004F;
pub const CKM_SHA512_T: CK_MECHANISM_TYPE = 0x00000050;
pub const CKM_SHA512_T_HMAC: CK_MECHANISM_TYPE = 0x00000051;
pub const CKM_SHA512_T_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000052;
pub const CKM_SHA512_T_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000053;
pub const CKM_SHA3_256_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000060;
pub const CKM_SHA3_384_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000061;
pub const CKM_SHA3_512_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000062;
pub const CKM_SHA3_256_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000063;
pub const CKM_SHA3_384_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000064;
pub const CKM_SHA3_512_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000065;
pub const CKM_SHA3_224_RSA_PKCS: CK_MECHANISM_TYPE = 0x00000066;
pub const CKM_SHA3_224_RSA_PKCS_PSS: CK_MECHANISM_TYPE = 0x00000067;
pub const CKM_RC2_KEY_GEN: CK_MECHANISM_TYPE = 0x00000100;
pub const CKM_RC2_ECB: CK_MECHANISM_TYPE = 0x00000101;
pub const CKM_RC2_CBC: CK_MECHANISM_TYPE = 0x00000102;
pub const CKM_RC2_MAC: CK_MECHANISM_TYPE = 0x00000103;
pub const CKM_RC2_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000104;
pub const CKM_RC2_CBC_PAD: CK_MECHANISM_TYPE = 0x00000105;
pub const CKM_RC4_KEY_GEN: CK_MECHANISM_TYPE = 0x00000110;
pub const CKM_RC4: CK_MECHANISM_TYPE = 0x00000111;
pub const CKM_DES_KEY_GEN: CK_MECHANISM_TYPE = 0x00000120;
pub const CKM_DES_ECB: CK_MECHANISM_TYPE = 0x00000121;
pub const CKM_DES_CBC: CK_MECHANISM_TYPE = 0x00000122;
pub const CKM_DES_MAC: CK_MECHANISM_TYPE = 0x00000123;
pub const CKM_DES_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000124;
pub const CKM_DES_CBC_PAD: CK_MECHANISM_TYPE = 0x00000125;
pub const CKM_DES2_KEY_GEN: CK_MECHANISM_TYPE = 0x00000130;
pub const CKM_DES3_KEY_GEN: CK_MECHANISM_TYPE = 0x00000131;
pub const CKM_DES3_ECB: CK_MECHANISM_TYPE = 0x00000132;
pub const CKM_DES3_CBC: CK_MECHANISM_TYPE = 0x00000133;
pub const CKM_DES3_MAC: CK_MECHANISM_TYPE = 0x00000134;
pub const CKM_DES3_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000135;
pub const CKM_DES3_CBC_PAD: CK_MECHANISM_TYPE = 0x00000136;
pub const CKM_DES3_CMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000137;
pub const CKM_DES3_CMAC: CK_MECHANISM_TYPE = 0x00000138;
pub const CKM_CDMF_KEY_GEN: CK_MECHANISM_TYPE = 0x00000140;
pub const CKM_CDMF_ECB: CK_MECHANISM_TYPE = 0x00000141;
pub const CKM_CDMF_CBC: CK_MECHANISM_TYPE = 0x00000142;
pub const CKM_CDMF_MAC: CK_MECHANISM_TYPE = 0x00000143;
pub const CKM_CDMF_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000144;
pub const CKM_CDMF_CBC_PAD: CK_MECHANISM_TYPE = 0x00000145;
pub const CKM_DES_OFB64: CK_MECHANISM_TYPE = 0x00000150;
pub const CKM_DES_OFB8: CK_MECHANISM_TYPE = 0x00000151;
pub const CKM_DES_CFB64: CK_MECHANISM_TYPE = 0x00000152;
pub const CKM_DES_CFB8: CK_MECHANISM_TYPE = 0x00000153;
pub const CKM_MD2: CK_MECHANISM_TYPE = 0x00000200;
pub const CKM_MD2_HMAC: CK_MECHANISM_TYPE = 0x00000201;
pub const CKM_MD2_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000202;
pub const CKM_MD5: CK_MECHANISM_TYPE = 0x00000210;
pub const CKM_MD5_HMAC: CK_MECHANISM_TYPE = 0x00000211;
pub const CKM_MD5_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000212;
pub const CKM_SHA_1: CK_MECHANISM_TYPE = 0x00000220;
pub const CKM_SHA_1_HMAC: CK_MECHANISM_TYPE = 0x00000221;
pub const CKM_SHA_1_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000222;
pub const CKM_RIPEMD128: CK_MECHANISM_TYPE = 0x00000230;
pub const CKM_RIPEMD128_HMAC: CK_MECHANISM_TYPE = 0x00000231;
pub const CKM_RIPEMD128_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000232;
pub const CKM_RIPEMD160: CK_MECHANISM_TYPE = 0x00000240;
pub const CKM_RIPEMD160_HMAC: CK_MECHANISM_TYPE = 0x00000241;
pub const CKM_RIPEMD160_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000242;
pub const CKM_SHA256: CK_MECHANISM_TYPE = 0x00000250;
pub const CKM_SHA256_HMAC: CK_MECHANISM_TYPE = 0x00000251;
pub const CKM_SHA256_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000252;
pub const CKM_SHA224: CK_MECHANISM_TYPE = 0x00000255;
pub const CKM_SHA224_HMAC: CK_MECHANISM_TYPE = 0x00000256;
pub const CKM_SHA224_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000257;
pub const CKM_SHA384: CK_MECHANISM_TYPE = 0x00000260;
pub const CKM_SHA384_HMAC: CK_MECHANISM_TYPE = 0x00000261;
pub const CKM_SHA384_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000262;
pub const CKM_SHA512: CK_MECHANISM_TYPE = 0x00000270;
pub const CKM_SHA512_HMAC: CK_MECHANISM_TYPE = 0x00000271;
pub const CKM_SHA512_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00000272;
pub const CKM_SECURID_KEY_GEN: CK_MECHANISM_TYPE = 0x00000280;
pub const CKM_SECURID: CK_MECHANISM_TYPE = 0x00000282;
pub const CKM_HOTP_KEY_GEN: CK_MECHANISM_TYPE = 0x00000290;
pub const CKM_HOTP: CK_MECHANISM_TYPE = 0x00000291;
pub const CKM_ACTI: CK_MECHANISM_TYPE = 0x000002A0;
pub const CKM_ACTI_KEY_GEN: CK_MECHANISM_TYPE = 0x000002A1;
pub const CKM_SHA3_256: CK_MECHANISM_TYPE = 0x000002B0;
pub const CKM_SHA3_256_HMAC: CK_MECHANISM_TYPE = 0x000002B1;
pub const CKM_SHA3_256_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x000002B2;
pub const CKM_SHA3_256_KEY_GEN: CK_MECHANISM_TYPE = 0x000002B3;
pub const CKM_SHA3_224: CK_MECHANISM_TYPE = 0x000002B5;
pub const CKM_SHA3_224_HMAC: CK_MECHANISM_TYPE = 0x000002B6;
pub const CKM_SHA3_224_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x000002B7;
pub const CKM_SHA3_224_KEY_GEN: CK_MECHANISM_TYPE = 0x000002B8;
pub const CKM_SHA3_384: CK_MECHANISM_TYPE = 0x000002C0;
pub const CKM_SHA3_384_HMAC: CK_MECHANISM_TYPE = 0x000002C1;
pub const CKM_SHA3_384_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x000002C2;
pub const CKM_SHA3_384_KEY_GEN: CK_MECHANISM_TYPE = 0x000002C3;
pub const CKM_SHA3_512: CK_MECHANISM_TYPE = 0x000002D0;
pub const CKM_SHA3_512_HMAC: CK_MECHANISM_TYPE = 0x000002D1;
pub const CKM_SHA3_512_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x000002D2;
pub const CKM_SHA3_512_KEY_GEN: CK_MECHANISM_TYPE = 0x000002D3;
pub const CKM_CAST_KEY_GEN: CK_MECHANISM_TYPE = 0x00000300;
pub const CKM_CAST_ECB: CK_MECHANISM_TYPE = 0x00000301;
pub const CKM_CAST_CBC: CK_MECHANISM_TYPE = 0x00000302;
pub const CKM_CAST_MAC: CK_MECHANISM_TYPE = 0x00000303;
pub const CKM_CAST_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000304;
pub const CKM_CAST_CBC_PAD: CK_MECHANISM_TYPE = 0x00000305;
pub const CKM_CAST3_KEY_GEN: CK_MECHANISM_TYPE = 0x00000310;
pub const CKM_CAST3_ECB: CK_MECHANISM_TYPE = 0x00000311;
pub const CKM_CAST3_CBC: CK_MECHANISM_TYPE = 0x00000312;
pub const CKM_CAST3_MAC: CK_MECHANISM_TYPE = 0x00000313;
pub const CKM_CAST3_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000314;
pub const CKM_CAST3_CBC_PAD: CK_MECHANISM_TYPE = 0x00000315;
pub const CKM_CAST128_KEY_GEN: CK_MECHANISM_TYPE = 0x00000320;
pub const CKM_CAST128_ECB: CK_MECHANISM_TYPE = 0x00000321;
pub const CKM_CAST128_CBC: CK_MECHANISM_TYPE = 0x00000322;
pub const CKM_CAST128_MAC: CK_MECHANISM_TYPE = 0x00000323;
pub const CKM_CAST128_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000324;
pub const CKM_CAST128_CBC_PAD: CK_MECHANISM_TYPE = 0x00000325;
pub const CKM_RC5_KEY_GEN: CK_MECHANISM_TYPE = 0x00000330;
pub const CKM_RC5_ECB: CK_MECHANISM_TYPE = 0x00000331;
pub const CKM_RC5_CBC: CK_MECHANISM_TYPE = 0x00000332;
pub const CKM_RC5_MAC: CK_MECHANISM_TYPE = 0x00000333;
pub const CKM_RC5_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000334;
pub const CKM_RC5_CBC_PAD: CK_MECHANISM_TYPE = 0x00000335;
pub const CKM_IDEA_KEY_GEN: CK_MECHANISM_TYPE = 0x00000340;
pub const CKM_IDEA_ECB: CK_MECHANISM_TYPE = 0x00000341;
pub const CKM_IDEA_CBC: CK_MECHANISM_TYPE = 0x00000342;
pub const CKM_IDEA_MAC: CK_MECHANISM_TYPE = 0x00000343;
pub const CKM_IDEA_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000344;
pub const CKM_IDEA_CBC_PAD: CK_MECHANISM_TYPE = 0x00000345;
pub const CKM_GENERIC_SECRET_KEY_GEN: CK_MECHANISM_TYPE = 0x00000350;
pub const CKM_CONCATENATE_BASE_AND_KEY: CK_MECHANISM_TYPE = 0x00000360;
pub const CKM_CONCATENATE_BASE_AND_DATA: CK_MECHANISM_TYPE = 0x00000362;
pub const CKM_CONCATENATE_DATA_AND_BASE: CK_MECHANISM_TYPE = 0x00000363;
pub const CKM_XOR_BASE_AND_DATA: CK_MECHANISM_TYPE = 0x00000364;
pub const CKM_EXTRACT_KEY_FROM_KEY: CK_MECHANISM_TYPE = 0x00000365;
pub const CKM_SSL3_PRE_MASTER_KEY_GEN: CK_MECHANISM_TYPE = 0x00000370;
pub const CKM_SSL3_MASTER_KEY_DERIVE: CK_MECHANISM_TYPE = 0x00000371;
pub const CKM_SSL3_KEY_AND_MAC_DERIVE: CK_MECHANISM_TYPE = 0x00000372;
pub const CKM_SSL3_MASTER_KEY_DERIVE_DH: CK_MECHANISM_TYPE = 0x00000373;
pub const CKM_TLS_PRE_MASTER_KEY_GEN: CK_MECHANISM_TYPE = 0x00000374;
pub const CKM_TLS_MASTER_KEY_DERIVE: CK_MECHANISM_TYPE = 0x00000375;
pub const CKM_TLS_KEY_AND_MAC_DERIVE: CK_MECHANISM_TYPE = 0x00000376;
pub const CKM_TLS_MASTER_KEY_DERIVE_DH: CK_MECHANISM_TYPE = 0x00000377;
pub const CKM_TLS_PRF: CK_MECHANISM_TYPE = 0x00000378;
pub const CKM_SSL3_MD5_MAC: CK_MECHANISM_TYPE = 0x00000380;
pub const CKM_SSL3_SHA1_MAC: CK_MECHANISM_TYPE = 0x00000381;
pub const CKM_MD5_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000390;
pub const CKM_MD2_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000391;
pub const CKM_SHA1_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000392;
pub const CKM_SHA256_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000393;
pub const CKM_SHA384_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000394;
pub const CKM_SHA512_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000395;
pub const CKM_SHA224_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000396;
pub const CKM_SHA3_256_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000397;
pub const CKM_SHA3_224_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000398;
pub const CKM_SHA3_384_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x00000399;
pub const CKM_SHA3_512_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x0000039A;
pub const CKM_SHAKE_128_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x0000039B;
pub const CKM_SHAKE_256_KEY_DERIVATION: CK_MECHANISM_TYPE = 0x0000039C;
pub const CKM_PBE_MD2_DES_CBC: CK_MECHANISM_TYPE = 0x000003A0;
pub const CKM_PBE_MD5_DES_CBC: CK_MECHANISM_TYPE = 0x000003A1;
pub const CKM_PBE_MD5_CAST_CBC: CK_MECHANISM_TYPE = 0x000003A2;
pub const CKM_PBE_MD5_CAST3_CBC: CK_MECHANISM_TYPE = 0x000003A3;
pub const CKM_PBE_MD5_CAST128_CBC: CK_MECHANISM_TYPE = 0x000003A4;
pub const CKM_PBE_SHA1_CAST128_CBC: CK_MECHANISM_TYPE = 0x000003A5;
pub const CKM_PBE_SHA1_RC4_128: CK_MECHANISM_TYPE = 0x000003A6;
pub const CKM_PBE_SHA1_RC4_40: CK_MECHANISM_TYPE = 0x000003A7;
pub const CKM_PBE_SHA1_DES3_EDE_CBC: CK_MECHANISM_TYPE = 0x000003A8;
pub const CKM_PBE_SHA1_DES2_EDE_CBC: CK_MECHANISM_TYPE = 0x000003A9;
pub const CKM_PBE_SHA1_RC2_128_CBC: CK_MECHANISM_TYPE = 0x000003AA;
pub const CKM_PBE_SHA1_RC2_40_CBC: CK_MECHANISM_TYPE = 0x000003AB;
pub const CKM_SP800_108_COUNTER_KDF: CK_MECHANISM_TYPE = 0x000003AC;
pub const CKM_SP800_108_FEEDBACK_KDF: CK_MECHANISM_TYPE = 0x000003AD;
pub const CKM_SP800_108_DOUBLE_PIPELINE_KDF: CK_MECHANISM_TYPE = 0x000003AE;
pub const CKM_PKCS5_PBKD2: CK_MECHANISM_TYPE = 0x000003B0;
pub const CKM_PBA_SHA1_WITH_SHA1_HMAC: CK_MECHANISM_TYPE = 0x000003C0;
pub const CKM_WTLS_PRE_MASTER_KEY_GEN: CK_MECHANISM_TYPE = 0x000003D0;
pub const CKM_WTLS_MASTER_KEY_DERIVE: CK_MECHANISM_TYPE = 0x000003D1;
pub const CKM_WTLS_MASTER_KEY_DERIVE_DH_ECC: CK_MECHANISM_TYPE = 0x000003D2;
pub const CKM_WTLS_PRF: CK_MECHANISM_TYPE = 0x000003D3;
pub const CKM_WTLS_SERVER_KEY_AND_MAC_DERIVE: CK_MECHANISM_TYPE = 0x000003D4;
pub const CKM_WTLS_CLIENT_KEY_AND_MAC_DERIVE: CK_MECHANISM_TYPE = 0x000003D5;
pub const CKM_TLS10_MAC_SERVER: CK_MECHANISM_TYPE = 0x000003D6;
pub const CKM_TLS10_MAC_CLIENT: CK_MECHANISM_TYPE = 0x000003D7;
pub const CKM_TLS12_MAC: CK_MECHANISM_TYPE = 0x000003D8;
pub const CKM_TLS12_KDF: CK_MECHANISM_TYPE = 0x000003D9;
pub const CKM_TLS12_MASTER_KEY_DERIVE: CK_MECHANISM_TYPE = 0x000003E0;
pub const CKM_TLS12_KEY_AND_MAC_DERIVE: CK_MECHANISM_TYPE = 0x000003E1;
pub const CKM_TLS12_MASTER_KEY_DERIVE_DH: CK_MECHANISM_TYPE = 0x000003E2;
pub const CKM_TLS12_KEY_SAFE_DERIVE: CK_MECHANISM_TYPE = 0x000003E3;
pub const CKM_TLS_MAC: CK_MECHANISM_TYPE = 0x000003E4;
pub const CKM_TLS_KDF: CK_MECHANISM_TYPE = 0x000003E5;
pub const CKM_KEY_WRAP_LYNKS: CK_MECHANISM_TYPE = 0x00000400;
pub const CKM_KEY_WRAP_SET_OAEP: CK_MECHANISM_TYPE = 0x00000401;
pub const CKM_CMS_SIG: CK_MECHANISM_TYPE = 0x00000500;
pub const CKM_KIP_DERIVE: CK_MECHANISM_TYPE = 0x00000510;
pub const CKM_KIP_WRAP: CK_MECHANISM_TYPE = 0x00000511;
pub const CKM_KIP_MAC: CK_MECHANISM_TYPE = 0x00000512;
pub const CKM_CAMELLIA_KEY_GEN: CK_MECHANISM_TYPE = 0x00000550;
pub const CKM_CAMELLIA_ECB: CK_MECHANISM_TYPE = 0x00000551;
pub const CKM_CAMELLIA_CBC: CK_MECHANISM_TYPE = 0x00000552;
pub const CKM_CAMELLIA_MAC: CK_MECHANISM_TYPE = 0x00000553;
pub const CKM_CAMELLIA_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000554;
pub const CKM_CAMELLIA_CBC_PAD: CK_MECHANISM_TYPE = 0x00000555;
pub const CKM_CAMELLIA_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000556;
pub const CKM_CAMELLIA_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000557;
pub const CKM_CAMELLIA_CTR: CK_MECHANISM_TYPE = 0x00000558;
pub const CKM_ARIA_KEY_GEN: CK_MECHANISM_TYPE = 0x00000560;
pub const CKM_ARIA_ECB: CK_MECHANISM_TYPE = 0x00000561;
pub const CKM_ARIA_CBC: CK_MECHANISM_TYPE = 0x00000562;
pub const CKM_ARIA_MAC: CK_MECHANISM_TYPE = 0x00000563;
pub const CKM_ARIA_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000564;
pub const CKM_ARIA_CBC_PAD: CK_MECHANISM_TYPE = 0x00000565;
pub const CKM_ARIA_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000566;
pub const CKM_ARIA_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000567;
pub const CKM_SEED_KEY_GEN: CK_MECHANISM_TYPE = 0x00000650;
pub const CKM_SEED_ECB: CK_MECHANISM_TYPE = 0x00000651;
pub const CKM_SEED_CBC: CK_MECHANISM_TYPE = 0x00000652;
pub const CKM_SEED_MAC: CK_MECHANISM_TYPE = 0x00000653;
pub const CKM_SEED_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00000654;
pub const CKM_SEED_CBC_PAD: CK_MECHANISM_TYPE = 0x00000655;
pub const CKM_SEED_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000656;
pub const CKM_SEED_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00000657;
pub const CKM_SKIPJACK_KEY_GEN: CK_MECHANISM_TYPE = 0x00001000;
pub const CKM_SKIPJACK_ECB64: CK_MECHANISM_TYPE = 0x00001001;
pub const CKM_SKIPJACK_CBC64: CK_MECHANISM_TYPE = 0x00001002;
pub const CKM_SKIPJACK_OFB64: CK_MECHANISM_TYPE = 0x00001003;
pub const CKM_SKIPJACK_CFB64: CK_MECHANISM_TYPE = 0x00001004;
pub const CKM_SKIPJACK_CFB32: CK_MECHANISM_TYPE = 0x00001005;
pub const CKM_SKIPJACK_CFB16: CK_MECHANISM_TYPE = 0x00001006;
pub const CKM_SKIPJACK_CFB8: CK_MECHANISM_TYPE = 0x00001007;
pub const CKM_SKIPJACK_WRAP: CK_MECHANISM_TYPE = 0x00001008;
pub const CKM_SKIPJACK_PRIVATE_WRAP: CK_MECHANISM_TYPE = 0x00001009;
pub const CKM_SKIPJACK_RELAYX: CK_MECHANISM_TYPE = 0x0000100A;
pub const CKM_KEA_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00001010;
pub const CKM_KEA_KEY_DERIVE: CK_MECHANISM_TYPE = 0x00001011;
pub const CKM_KEA_DERIVE: CK_MECHANISM_TYPE = 0x00001012;
pub const CKM_FORTEZZA_TIMESTAMP: CK_MECHANISM_TYPE = 0x00001020;
pub const CKM_BATON_KEY_GEN: CK_MECHANISM_TYPE = 0x00001030;
pub const CKM_BATON_ECB128: CK_MECHANISM_TYPE = 0x00001031;
pub const CKM_BATON_ECB96: CK_MECHANISM_TYPE = 0x00001032;
pub const CKM_BATON_CBC128: CK_MECHANISM_TYPE = 0x00001033;
pub const CKM_BATON_COUNTER: CK_MECHANISM_TYPE = 0x00001034;
pub const CKM_BATON_SHUFFLE: CK_MECHANISM_TYPE = 0x00001035;
pub const CKM_BATON_WRAP: CK_MECHANISM_TYPE = 0x00001036;
pub const CKM_EC_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00001040;
pub const CKM_ECDSA: CK_MECHANISM_TYPE = 0x00001041;
pub const CKM_ECDSA_SHA1: CK_MECHANISM_TYPE = 0x00001042;
pub const CKM_ECDSA_SHA224: CK_MECHANISM_TYPE = 0x00001043;
pub const CKM_ECDSA_SHA256: CK_MECHANISM_TYPE = 0x00001044;
pub const CKM_ECDSA_SHA384: CK_MECHANISM_TYPE = 0x00001045;
pub const CKM_ECDSA_SHA512: CK_MECHANISM_TYPE = 0x00001046;
pub const CKM_ECDSA_SHA3_224: CK_MECHANISM_TYPE = 0x00001047;
pub const CKM_ECDSA_SHA3_256: CK_MECHANISM_TYPE = 0x00001048;
pub const CKM_ECDSA_SHA3_384: CK_MECHANISM_TYPE = 0x00001049;
pub const CKM_ECDSA_SHA3_512: CK_MECHANISM_TYPE = 0x0000104A;
pub const CKM_ECDH1_DERIVE: CK_MECHANISM_TYPE = 0x00001050;
pub const CKM_ECDH1_COFACTOR_DERIVE: CK_MECHANISM_TYPE = 0x00001051;
pub const CKM_ECMQV_DERIVE: CK_MECHANISM_TYPE = 0x00001052;
pub const CKM_ECDH_AES_KEY_WRAP: CK_MECHANISM_TYPE = 0x00001053;
pub const CKM_RSA_AES_KEY_WRAP: CK_MECHANISM_TYPE = 0x00001054;
pub const CKM_EC_EDWARDS_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00001055;
pub const CKM_EC_MONTGOMERY_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00001056;
pub const CKM_EDDSA: CK_MECHANISM_TYPE = 0x00001057;
pub const CKM_JUNIPER_KEY_GEN: CK_MECHANISM_TYPE = 0x00001060;
pub const CKM_JUNIPER_ECB128: CK_MECHANISM_TYPE = 0x00001061;
pub const CKM_JUNIPER_CBC128: CK_MECHANISM_TYPE = 0x00001062;
pub const CKM_JUNIPER_COUNTER: CK_MECHANISM_TYPE = 0x00001063;
pub const CKM_JUNIPER_SHUFFLE: CK_MECHANISM_TYPE = 0x00001064;
pub const CKM_JUNIPER_WRAP: CK_MECHANISM_TYPE = 0x00001065;
pub const CKM_FASTHASH: CK_MECHANISM_TYPE = 0x00001070;
pub const CKM_AES_XTS: CK_MECHANISM_TYPE = 0x00001071;
pub const CKM_AES_XTS_KEY_GEN: CK_MECHANISM_TYPE = 0x00001072;
pub const CKM_AES_KEY_GEN: CK_MECHANISM_TYPE = 0x00001080;
pub const CKM_AES_ECB: CK_MECHANISM_TYPE = 0x00001081;
pub const CKM_AES_CBC: CK_MECHANISM_TYPE = 0x00001082;
pub const CKM_AES_MAC: CK_MECHANISM_TYPE = 0x00001083;
pub const CKM_AES_MAC_GENERAL: CK_MECHANISM_TYPE = 0x00001084;
pub const CKM_AES_CBC_PAD: CK_MECHANISM_TYPE = 0x00001085;
pub const CKM_AES_CTR: CK_MECHANISM_TYPE = 0x00001086;
pub const CKM_AES_GCM: CK_MECHANISM_TYPE = 0x00001087;
pub const CKM_AES_CCM: CK_MECHANISM_TYPE = 0x00001088;
pub const CKM_AES_CTS: CK_MECHANISM_TYPE = 0x00001089;
pub const CKM_AES_CMAC: CK_MECHANISM_TYPE = 0x0000108A;
pub const CKM_AES_CMAC_GENERAL: CK_MECHANISM_TYPE = 0x0000108B;
pub const CKM_AES_XCBC_MAC: CK_MECHANISM_TYPE = 0x0000108C;
pub const CKM_AES_XCBC_MAC_96: CK_MECHANISM_TYPE = 0x0000108D;
pub const CKM_AES_GMAC: CK_MECHANISM_TYPE = 0x0000108E;
pub const CKM_BLOWFISH_KEY_GEN: CK_MECHANISM_TYPE = 0x00001090;
pub const CKM_BLOWFISH_CBC: CK_MECHANISM_TYPE = 0x00001091;
pub const CKM_TWOFISH_KEY_GEN: CK_MECHANISM_TYPE = 0x00001092;
pub const CKM_TWOFISH_CBC: CK_MECHANISM_TYPE = 0x00001093;
pub const CKM_BLOWFISH_CBC_PAD: CK_MECHANISM_TYPE = 0x00001094;
pub const CKM_TWOFISH_CBC_PAD: CK_MECHANISM_TYPE = 0x00001095;
pub const CKM_DES_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001100;
pub const CKM_DES_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001101;
pub const CKM_DES3_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001102;
pub const CKM_DES3_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001103;
pub const CKM_AES_ECB_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001104;
pub const CKM_AES_CBC_ENCRYPT_DATA: CK_MECHANISM_TYPE = 0x00001105;
pub const CKM_GOSTR3410_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00001200;
pub const CKM_GOSTR3410: CK_MECHANISM_TYPE = 0x00001201;
pub const CKM_GOSTR3410_WITH_GOSTR3411: CK_MECHANISM_TYPE = 0x00001202;
pub const CKM_GOSTR3410_KEY_WRAP: CK_MECHANISM_TYPE = 0x00001203;
pub const CKM_GOSTR3410_DERIVE: CK_MECHANISM_TYPE = 0x00001204;
pub const CKM_GOSTR3411: CK_MECHANISM_TYPE = 0x00001210;
pub const CKM_GOSTR3411_HMAC: CK_MECHANISM_TYPE = 0x00001211;
pub const CKM_GOST28147_KEY_GEN: CK_MECHANISM_TYPE = 0x00001220;
pub const CKM_GOST28147_ECB: CK_MECHANISM_TYPE = 0x00001221;
pub const CKM_GOST28147: CK_MECHANISM_TYPE = 0x00001222;
pub const CKM_GOST28147_MAC: CK_MECHANISM_TYPE = 0x00001223;
pub const CKM_GOST28147_KEY_WRAP: CK_MECHANISM_TYPE = 0x00001224;
pub const CKM_CHACHA20_KEY_GEN: CK_MECHANISM_TYPE = 0x00001225;
pub const CKM_CHACHA20: CK_MECHANISM_TYPE = 0x00001226;
pub const CKM_POLY1305_KEY_GEN: CK_MECHANISM_TYPE = 0x00001227;
pub const CKM_POLY1305: CK_MECHANISM_TYPE = 0x00001228;
pub const CKM_EC_KEY_PAIR_GEN_W_EXTRA_BITS: CK_MECHANISM_TYPE = 0x0000140B;
pub const CKM_DSA_PARAMETER_GEN: CK_MECHANISM_TYPE = 0x00002000;
pub const CKM_DH_PKCS_PARAMETER_GEN: CK_MECHANISM_TYPE = 0x00002001;
pub const CKM_X9_42_DH_PARAMETER_GEN: CK_MECHANISM_TYPE = 0x00002002;
pub const CKM_DSA_PROBABILISTIC_PARAMETER_GEN: CK_MECHANISM_TYPE = 0x00002003;
pub const CKM_DSA_SHAWE_TAYLOR_PARAMETER_GEN: CK_MECHANISM_TYPE = 0x00002004;
pub const CKM_DSA_FIPS_G_GEN: CK_MECHANISM_TYPE = 0x00002005;
pub const CKM_AES_OFB: CK_MECHANISM_TYPE = 0x00002104;
pub const CKM_AES_CFB64: CK_MECHANISM_TYPE = 0x00002105;
pub const CKM_AES_CFB8: CK_MECHANISM_TYPE = 0x00002106;
pub const CKM_AES_CFB128: CK_MECHANISM_TYPE = 0x00002107;
pub const CKM_AES_CFB1: CK_MECHANISM_TYPE = 0x00002108;
pub const CKM_AES_KEY_WRAP: CK_MECHANISM_TYPE = 0x00002109;
pub const CKM_AES_KEY_WRAP_PAD: CK_MECHANISM_TYPE = 0x0000210A;
pub const CKM_AES_KEY_WRAP_KWP: CK_MECHANISM_TYPE = 0x0000210B;
pub const CKM_AES_KEY_WRAP_PKCS7: CK_MECHANISM_TYPE = 0x0000210C;
pub const CKM_RSA_PKCS_TPM_1_1: CK_MECHANISM_TYPE = 0x00004001;
pub const CKM_RSA_PKCS_OAEP_TPM_1_1: CK_MECHANISM_TYPE = 0x00004002;
pub const CKM_SHA_1_KEY_GEN: CK_MECHANISM_TYPE = 0x00004003;
pub const CKM_SHA224_KEY_GEN: CK_MECHANISM_TYPE = 0x00004004;
pub const CKM_SHA256_KEY_GEN: CK_MECHANISM_TYPE = 0x00004005;
pub const CKM_SHA384_KEY_GEN: CK_MECHANISM_TYPE = 0x00004006;
pub const CKM_SHA512_KEY_GEN: CK_MECHANISM_TYPE = 0x00004007;
pub const CKM_SHA512_224_KEY_GEN: CK_MECHANISM_TYPE = 0x00004008;
pub const CKM_SHA512_256_KEY_GEN: CK_MECHANISM_TYPE = 0x00004009;
pub const CKM_SHA512_T_KEY_GEN: CK_MECHANISM_TYPE = 0x0000400A;
pub const CKM_NULL: CK_MECHANISM_TYPE = 0x0000400B;
pub const CKM_BLAKE2B_160: CK_MECHANISM_TYPE = 0x0000400C;
pub const CKM_BLAKE2B_160_HMAC: CK_MECHANISM_TYPE = 0x0000400D;
pub const CKM_BLAKE2B_160_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x0000400E;
pub const CKM_BLAKE2B_160_KEY_DERIVE: CK_MECHANISM_TYPE = 0x0000400F;
pub const CKM_BLAKE2B_160_KEY_GEN: CK_MECHANISM_TYPE = 0x00004010;
pub const CKM_BLAKE2B_256: CK_MECHANISM_TYPE = 0x00004011;
pub const CKM_BLAKE2B_256_HMAC: CK_MECHANISM_TYPE = 0x00004012;
pub const CKM_BLAKE2B_256_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00004013;
pub const CKM_BLAKE2B_256_KEY_DERIVE: CK_MECHANISM_TYPE = 0x00004014;
pub const CKM_BLAKE2B_256_KEY_GEN: CK_MECHANISM_TYPE = 0x00004015;
pub const CKM_BLAKE2B_384: CK_MECHANISM_TYPE = 0x00004016;
pub const CKM_BLAKE2B_384_HMAC: CK_MECHANISM_TYPE = 0x00004017;
pub const CKM_BLAKE2B_384_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x00004018;
pub const CKM_BLAKE2B_384_KEY_DERIVE: CK_MECHANISM_TYPE = 0x00004019;
pub const CKM_BLAKE2B_384_KEY_GEN: CK_MECHANISM_TYPE = 0x0000401A;
pub const CKM_BLAKE2B_512: CK_MECHANISM_TYPE = 0x0000401B;
pub const CKM_BLAKE2B_512_HMAC: CK_MECHANISM_TYPE = 0x0000401C;
pub const CKM_BLAKE2B_512_HMAC_GENERAL: CK_MECHANISM_TYPE = 0x0000401D;
pub const CKM_BLAKE2B_512_KEY_DERIVE: CK_MECHANISM_TYPE = 0x0000401E;
pub const CKM_BLAKE2B_512_KEY_GEN: CK_MECHANISM_TYPE = 0x0000401F;
pub const CKM_SALSA20: CK_MECHANISM_TYPE = 0x00004020;
pub const CKM_CHACHA20_POLY1305: CK_MECHANISM_TYPE = 0x00004021;
pub const CKM_SALSA20_POLY1305: CK_MECHANISM_TYPE = 0x00004022;
pub const CKM_X3DH_INITIALIZE: CK_MECHANISM_TYPE = 0x00004023;
pub const CKM_X3DH_RESPOND: CK_MECHANISM_TYPE = 0x00004024;
pub const CKM_X2RATCHET_INITIALIZE: CK_MECHANISM_TYPE = 0x00004025;
pub const CKM_X2RATCHET_RESPOND: CK_MECHANISM_TYPE = 0x00004026;
pub const CKM_X2RATCHET_ENCRYPT: CK_MECHANISM_TYPE = 0x00004027;
pub const CKM_X2RATCHET_DECRYPT: CK_MECHANISM_TYPE = 0x00004028;
pub const CKM_XEDDSA: CK_MECHANISM_TYPE = 0x00004029;
pub const CKM_HKDF_DERIVE: CK_MECHANISM_TYPE = 0x0000402A;
pub const CKM_HKDF_DATA: CK_MECHANISM_TYPE = 0x0000402B;
pub const CKM_HKDF_KEY_GEN: CK_MECHANISM_TYPE = 0x0000402C;
pub const CKM_SALSA20_KEY_GEN: CK_MECHANISM_TYPE = 0x0000402D;
pub const CKM_IKE2_PRF_PLUS_DERIVE: CK_MECHANISM_TYPE = 0x0000402E;
pub const CKM_IKE_PRF_DERIVE: CK_MECHANISM_TYPE = 0x0000402F;
pub const CKM_IKE1_PRF_DERIVE: CK_MECHANISM_TYPE = 0x00004030;
pub const CKM_IKE1_EXTENDED_DERIVE: CK_MECHANISM_TYPE = 0x00004031;
pub const CKM_HSS_KEY_PAIR_GEN: CK_MECHANISM_TYPE = 0x00004032;
pub const CKM_HSS: CK_MECHANISM_TYPE = 0x00004033;
pub const CKM_VENDOR_DEFINED: CK_MECHANISM_TYPE = 0x80000000;

// Structs.

pub const CK_DATE = extern struct {
    year: [4]CK_CHAR,
    month: [2]CK_CHAR,
    day: [2]CK_CHAR,
};

pub const CK_VERSION = extern struct {
    major: CK_BYTE,
    minor: CK_BYTE,
};

pub const CK_INFO = extern struct {
    cryptokiVersion: CK_VERSION,
    manufacturerID: [32]CK_UTF8CHAR,
    flags: CK_FLAGS,
    libraryDescription: [32]CK_UTF8CHAR,
    libraryVersion: CK_VERSION,
};

pub const CK_SLOT_INFO = extern struct {
    slotDescription: [64]CK_UTF8CHAR,
    manufacturerID: [32]CK_UTF8CHAR,
    flags: CK_FLAGS,
    hardwareVersion: CK_VERSION,
    firmwareVersion: CK_VERSION,
};

pub const CK_TOKEN_INFO = extern struct {
    label: [32]CK_UTF8CHAR,
    manufacturerID: [32]CK_UTF8CHAR,
    model: [16]CK_UTF8CHAR,
    serialNumber: [16]CK_CHAR,
    flags: CK_FLAGS,
    ulMaxSessionCount: CK_ULONG,
    ulSessionCount: CK_ULONG,
    ulMaxRwSessionCount: CK_ULONG,
    ulRwSessionCount: CK_ULONG,
    ulMaxPinLen: CK_ULONG,
    ulMinPinLen: CK_ULONG,
    ulTotalPublicMemory: CK_ULONG,
    ulFreePublicMemory: CK_ULONG,
    ulTotalPrivateMemory: CK_ULONG,
    ulFreePrivateMemory: CK_ULONG,
    hardwareVersion: CK_VERSION,
    firmwareVersion: CK_VERSION,
    utcTime: [16]CK_CHAR,
};

pub const CK_SESSION_INFO = extern struct {
    slotID: CK_SLOT_ID,
    state: CK_ULONG,
    flags: CK_FLAGS,
    ulDeviceError: CK_ULONG,
};

pub const CK_ATTRIBUTE = extern struct {
    type: CK_ATTRIBUTE_TYPE,
    pValue: CK_VOID_PTR,
    ulValueLen: CK_ULONG,
};

pub const CK_MECHANISM = extern struct {
    mechanism: CK_MECHANISM_TYPE,
    pParameter: CK_VOID_PTR,
    ulParameterLen: CK_ULONG,
};

pub const CK_MECHANISM_INFO = extern struct {
    ulMinKeySize: CK_ULONG,
    ulMaxKeySize: CK_ULONG,
    flags: CK_FLAGS,
};

// Callback types.
pub const CK_NOTIFY = ?*const fn (CK_SESSION_HANDLE, CK_NOTIFICATION, CK_VOID_PTR) callconv(.c) CK_RV;
pub const CK_CREATEMUTEX = ?*const fn (*CK_VOID_PTR) callconv(.c) CK_RV;
pub const CK_DESTROYMUTEX = ?*const fn (CK_VOID_PTR) callconv(.c) CK_RV;
pub const CK_LOCKMUTEX = ?*const fn (CK_VOID_PTR) callconv(.c) CK_RV;
pub const CK_UNLOCKMUTEX = ?*const fn (CK_VOID_PTR) callconv(.c) CK_RV;

pub const CK_C_INITIALIZE_ARGS = extern struct {
    CreateMutex: CK_CREATEMUTEX,
    DestroyMutex: CK_DESTROYMUTEX,
    LockMutex: CK_LOCKMUTEX,
    UnlockMutex: CK_UNLOCKMUTEX,
    flags: CK_FLAGS,
    pReserved: CK_VOID_PTR,
};

// Return values.
pub const CK_RV = CK_ULONG;

pub const CKR_OK: CK_RV = 0x00000000;
pub const CKR_CANCEL: CK_RV = 0x00000001;
pub const CKR_HOST_MEMORY: CK_RV = 0x00000002;
pub const CKR_SLOT_ID_INVALID: CK_RV = 0x00000003;
pub const CKR_GENERAL_ERROR: CK_RV = 0x00000005;
pub const CKR_FUNCTION_FAILED: CK_RV = 0x00000006;
pub const CKR_ARGUMENTS_BAD: CK_RV = 0x00000007;
pub const CKR_NO_EVENT: CK_RV = 0x00000008;
pub const CKR_NEED_TO_CREATE_THREADS: CK_RV = 0x00000009;
pub const CKR_CANT_LOCK: CK_RV = 0x0000000A;
pub const CKR_ATTRIBUTE_READ_ONLY: CK_RV = 0x00000010;
pub const CKR_ATTRIBUTE_SENSITIVE: CK_RV = 0x00000011;
pub const CKR_ATTRIBUTE_TYPE_INVALID: CK_RV = 0x00000012;
pub const CKR_ATTRIBUTE_VALUE_INVALID: CK_RV = 0x00000013;
pub const CKR_ACTION_PROHIBITED: CK_RV = 0x0000001B;
pub const CKR_DATA_INVALID: CK_RV = 0x00000020;
pub const CKR_DATA_LEN_RANGE: CK_RV = 0x00000021;
pub const CKR_DEVICE_ERROR: CK_RV = 0x00000030;
pub const CKR_DEVICE_MEMORY: CK_RV = 0x00000031;
pub const CKR_DEVICE_REMOVED: CK_RV = 0x00000032;
pub const CKR_ENCRYPTED_DATA_INVALID: CK_RV = 0x00000040;
pub const CKR_ENCRYPTED_DATA_LEN_RANGE: CK_RV = 0x00000041;
pub const CKR_AEAD_DECRYPT_FAILED: CK_RV = 0x00000042;
pub const CKR_FUNCTION_CANCELED: CK_RV = 0x00000050;
pub const CKR_FUNCTION_NOT_PARALLEL: CK_RV = 0x00000051;
pub const CKR_FUNCTION_NOT_SUPPORTED: CK_RV = 0x00000054;
pub const CKR_KEY_HANDLE_INVALID: CK_RV = 0x00000060;
pub const CKR_KEY_SIZE_RANGE: CK_RV = 0x00000062;
pub const CKR_KEY_TYPE_INCONSISTENT: CK_RV = 0x00000063;
pub const CKR_KEY_NOT_NEEDED: CK_RV = 0x00000064;
pub const CKR_KEY_CHANGED: CK_RV = 0x00000065;
pub const CKR_KEY_NEEDED: CK_RV = 0x00000066;
pub const CKR_KEY_INDIGESTIBLE: CK_RV = 0x00000067;
pub const CKR_KEY_FUNCTION_NOT_PERMITTED: CK_RV = 0x00000068;
pub const CKR_KEY_NOT_WRAPPABLE: CK_RV = 0x00000069;
pub const CKR_KEY_UNEXTRACTABLE: CK_RV = 0x0000006A;
pub const CKR_MECHANISM_INVALID: CK_RV = 0x00000070;
pub const CKR_MECHANISM_PARAM_INVALID: CK_RV = 0x00000071;
pub const CKR_OBJECT_HANDLE_INVALID: CK_RV = 0x00000082;
pub const CKR_OPERATION_ACTIVE: CK_RV = 0x00000090;
pub const CKR_OPERATION_NOT_INITIALIZED: CK_RV = 0x00000091;
pub const CKR_PIN_INCORRECT: CK_RV = 0x000000A0;
pub const CKR_PIN_INVALID: CK_RV = 0x000000A1;
pub const CKR_PIN_LEN_RANGE: CK_RV = 0x000000A2;
pub const CKR_PIN_EXPIRED: CK_RV = 0x000000A3;
pub const CKR_PIN_LOCKED: CK_RV = 0x000000A4;
pub const CKR_SESSION_CLOSED: CK_RV = 0x000000B0;
pub const CKR_SESSION_COUNT: CK_RV = 0x000000B1;
pub const CKR_SESSION_HANDLE_INVALID: CK_RV = 0x000000B3;
pub const CKR_SESSION_PARALLEL_NOT_SUPPORTED: CK_RV = 0x000000B4;
pub const CKR_SESSION_READ_ONLY: CK_RV = 0x000000B5;
pub const CKR_SESSION_EXISTS: CK_RV = 0x000000B6;
pub const CKR_SESSION_READ_ONLY_EXISTS: CK_RV = 0x000000B7;
pub const CKR_SESSION_READ_WRITE_SO_EXISTS: CK_RV = 0x000000B8;
pub const CKR_SIGNATURE_INVALID: CK_RV = 0x000000C0;
pub const CKR_SIGNATURE_LEN_RANGE: CK_RV = 0x000000C1;
pub const CKR_TEMPLATE_INCOMPLETE: CK_RV = 0x000000D0;
pub const CKR_TEMPLATE_INCONSISTENT: CK_RV = 0x000000D1;
pub const CKR_TOKEN_NOT_PRESENT: CK_RV = 0x000000E0;
pub const CKR_TOKEN_NOT_RECOGNIZED: CK_RV = 0x000000E1;
pub const CKR_TOKEN_WRITE_PROTECTED: CK_RV = 0x000000E2;
pub const CKR_UNWRAPPING_KEY_HANDLE_INVALID: CK_RV = 0x000000F0;
pub const CKR_UNWRAPPING_KEY_SIZE_RANGE: CK_RV = 0x000000F1;
pub const CKR_UNWRAPPING_KEY_TYPE_INCONSISTENT: CK_RV = 0x000000F2;
pub const CKR_USER_ALREADY_LOGGED_IN: CK_RV = 0x00000100;
pub const CKR_USER_NOT_LOGGED_IN: CK_RV = 0x00000101;
pub const CKR_USER_PIN_NOT_INITIALIZED: CK_RV = 0x00000102;
pub const CKR_USER_TYPE_INVALID: CK_RV = 0x00000103;
pub const CKR_USER_ANOTHER_ALREADY_LOGGED_IN: CK_RV = 0x00000104;
pub const CKR_USER_TOO_MANY_TYPES: CK_RV = 0x00000105;
pub const CKR_WRAPPED_KEY_INVALID: CK_RV = 0x00000110;
pub const CKR_WRAPPED_KEY_LEN_RANGE: CK_RV = 0x00000112;
pub const CKR_WRAPPING_KEY_HANDLE_INVALID: CK_RV = 0x00000113;
pub const CKR_WRAPPING_KEY_SIZE_RANGE: CK_RV = 0x00000114;
pub const CKR_WRAPPING_KEY_TYPE_INCONSISTENT: CK_RV = 0x00000115;
pub const CKR_RANDOM_SEED_NOT_SUPPORTED: CK_RV = 0x00000120;
pub const CKR_RANDOM_NO_RNG: CK_RV = 0x00000121;
pub const CKR_DOMAIN_PARAMS_INVALID: CK_RV = 0x00000130;
pub const CKR_CURVE_NOT_SUPPORTED: CK_RV = 0x00000140;
pub const CKR_BUFFER_TOO_SMALL: CK_RV = 0x00000150;
pub const CKR_SAVED_STATE_INVALID: CK_RV = 0x00000160;
pub const CKR_INFORMATION_SENSITIVE: CK_RV = 0x00000170;
pub const CKR_STATE_UNSAVEABLE: CK_RV = 0x00000180;
pub const CKR_CRYPTOKI_NOT_INITIALIZED: CK_RV = 0x00000190;
pub const CKR_CRYPTOKI_ALREADY_INITIALIZED: CK_RV = 0x00000191;
pub const CKR_MUTEX_BAD: CK_RV = 0x000001A0;
pub const CKR_MUTEX_NOT_LOCKED: CK_RV = 0x000001A1;
pub const CKR_NEW_PIN_MODE: CK_RV = 0x000001B0;
pub const CKR_NEXT_OTP: CK_RV = 0x000001B1;
pub const CKR_EXCEEDED_MAX_ITERATIONS: CK_RV = 0x000001B5;
pub const CKR_FIPS_SELF_TEST_FAILED: CK_RV = 0x000001B6;
pub const CKR_LIBRARY_LOAD_FAILED: CK_RV = 0x000001B7;
pub const CKR_PIN_TOO_WEAK: CK_RV = 0x000001B8;
pub const CKR_PUBLIC_KEY_INVALID: CK_RV = 0x000001B9;
pub const CKR_FUNCTION_REJECTED: CK_RV = 0x00000200;
pub const CKR_TOKEN_RESOURCE_EXCEEDED: CK_RV = 0x00000201;
pub const CKR_OPERATION_CANCEL_FAILED: CK_RV = 0x00000202;
pub const CKR_KEY_EXHAUSTED: CK_RV = 0x00000203;
pub const CKR_VENDOR_DEFINED: CK_RV = 0x80000000;

// Slot info flags.
pub const CKF_TOKEN_PRESENT: CK_FLAGS = 0x00000001;
pub const CKF_REMOVABLE_DEVICE: CK_FLAGS = 0x00000002;
pub const CKF_HW_SLOT: CK_FLAGS = 0x00000004;

// Token info flags.
pub const CKF_RNG: CK_FLAGS = 0x00000001;
pub const CKF_WRITE_PROTECTED: CK_FLAGS = 0x00000002;
pub const CKF_LOGIN_REQUIRED: CK_FLAGS = 0x00000004;
pub const CKF_USER_PIN_INITIALIZED: CK_FLAGS = 0x00000008;
pub const CKF_RESTORE_KEY_NOT_NEEDED: CK_FLAGS = 0x00000020;
pub const CKF_CLOCK_ON_TOKEN: CK_FLAGS = 0x00000040;
pub const CKF_PROTECTED_AUTHENTICATION_PATH: CK_FLAGS = 0x00000100;
pub const CKF_DUAL_CRYPTO_OPERATIONS: CK_FLAGS = 0x00000200;
pub const CKF_TOKEN_INITIALIZED: CK_FLAGS = 0x00000400;
pub const CKF_SECONDARY_AUTHENTICATION: CK_FLAGS = 0x00000800;
pub const CKF_USER_PIN_COUNT_LOW: CK_FLAGS = 0x00010000;
pub const CKF_USER_PIN_FINAL_TRY: CK_FLAGS = 0x00020000;
pub const CKF_USER_PIN_LOCKED: CK_FLAGS = 0x00040000;
pub const CKF_USER_PIN_TO_BE_CHANGED: CK_FLAGS = 0x00080000;
pub const CKF_SO_PIN_COUNT_LOW: CK_FLAGS = 0x00100000;
pub const CKF_SO_PIN_FINAL_TRY: CK_FLAGS = 0x00200000;
pub const CKF_SO_PIN_LOCKED: CK_FLAGS = 0x00400000;
pub const CKF_SO_PIN_TO_BE_CHANGED: CK_FLAGS = 0x00800000;
pub const CKF_ERROR_STATE: CK_FLAGS = 0x01000000;

// Session flags.
pub const CKF_RW_SESSION: CK_FLAGS = 0x00000002;
pub const CKF_SERIAL_SESSION: CK_FLAGS = 0x00000004;

// Mechanism info flags.
pub const CKF_HW: CK_FLAGS = 0x00000001;
pub const CKF_MESSAGE_ENCRYPT: CK_FLAGS = 0x00000002;
pub const CKF_MESSAGE_DECRYPT: CK_FLAGS = 0x00000004;
pub const CKF_MESSAGE_SIGN: CK_FLAGS = 0x00000008;
pub const CKF_MESSAGE_VERIFY: CK_FLAGS = 0x00000010;
pub const CKF_MULTI_MESSAGE: CK_FLAGS = 0x00000020;
pub const CKF_FIND_OBJECTS: CK_FLAGS = 0x00000040;
pub const CKF_ENCRYPT: CK_FLAGS = 0x00000100;
pub const CKF_DECRYPT: CK_FLAGS = 0x00000200;
pub const CKF_DIGEST: CK_FLAGS = 0x00000400;
pub const CKF_SIGN: CK_FLAGS = 0x00000800;
pub const CKF_SIGN_RECOVER: CK_FLAGS = 0x00001000;
pub const CKF_VERIFY: CK_FLAGS = 0x00002000;
pub const CKF_VERIFY_RECOVER: CK_FLAGS = 0x00004000;
pub const CKF_GENERATE: CK_FLAGS = 0x00008000;
pub const CKF_GENERATE_KEY_PAIR: CK_FLAGS = 0x00010000;
pub const CKF_WRAP: CK_FLAGS = 0x00020000;
pub const CKF_UNWRAP: CK_FLAGS = 0x00040000;
pub const CKF_DERIVE: CK_FLAGS = 0x00080000;
pub const CKF_EC_F_P: CK_FLAGS = 0x00100000;
pub const CKF_EC_F_2M: CK_FLAGS = 0x00200000;
pub const CKF_EC_ECPARAMETERS: CK_FLAGS = 0x00400000;
pub const CKF_EC_OID: CK_FLAGS = 0x00800000;
pub const CKF_EC_UNCOMPRESS: CK_FLAGS = 0x01000000;
pub const CKF_EC_COMPRESS: CK_FLAGS = 0x02000000;
pub const CKF_EC_CURVENAME: CK_FLAGS = 0x04000000;
pub const CKF_EXTENSION: CK_FLAGS = 0x80000000;

// WaitForSlotEvent flag.
pub const CKF_DONT_BLOCK: CK_FLAGS = 1;

// Initialize args flags.
pub const CKF_LIBRARY_CANT_CREATE_OS_THREADS: CK_FLAGS = 0x00000001;
pub const CKF_OS_LOCKING_OK: CK_FLAGS = 0x00000002;

// CK_FUNCTION_LIST matches the v2.x layout: CK_VERSION followed by
// function pointers in the exact order defined in pkcs11f.h (excluding
// v3.0+ additions guarded by CK_PKCS11_2_0_ONLY).
pub const CK_FUNCTION_LIST = extern struct {
    version: CK_VERSION,

    // General purpose
    C_Initialize: ?*const fn (CK_VOID_PTR) callconv(.c) CK_RV,
    C_Finalize: ?*const fn (CK_VOID_PTR) callconv(.c) CK_RV,
    C_GetInfo: ?*const fn (*CK_INFO) callconv(.c) CK_RV,
    C_GetFunctionList: ?*const fn (*?*CK_FUNCTION_LIST) callconv(.c) CK_RV,

    // Slot and token management
    C_GetSlotList: ?*const fn (CK_BBOOL, ?[*]CK_SLOT_ID, *CK_ULONG) callconv(.c) CK_RV,
    C_GetSlotInfo: ?*const fn (CK_SLOT_ID, *CK_SLOT_INFO) callconv(.c) CK_RV,
    C_GetTokenInfo: ?*const fn (CK_SLOT_ID, *CK_TOKEN_INFO) callconv(.c) CK_RV,
    C_GetMechanismList: ?*const fn (CK_SLOT_ID, ?[*]CK_MECHANISM_TYPE, *CK_ULONG) callconv(.c) CK_RV,
    C_GetMechanismInfo: ?*const fn (CK_SLOT_ID, CK_MECHANISM_TYPE, *CK_MECHANISM_INFO) callconv(.c) CK_RV,
    C_InitToken: ?*const fn (CK_SLOT_ID, CK_UTF8CHAR_PTR, CK_ULONG, CK_UTF8CHAR_PTR) callconv(.c) CK_RV,
    C_InitPIN: ?*const fn (CK_SESSION_HANDLE, CK_UTF8CHAR_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_SetPIN: ?*const fn (CK_SESSION_HANDLE, CK_UTF8CHAR_PTR, CK_ULONG, CK_UTF8CHAR_PTR, CK_ULONG) callconv(.c) CK_RV,

    // Session management
    C_OpenSession: ?*const fn (CK_SLOT_ID, CK_FLAGS, CK_VOID_PTR, CK_NOTIFY, *CK_SESSION_HANDLE) callconv(.c) CK_RV,
    C_CloseSession: ?*const fn (CK_SESSION_HANDLE) callconv(.c) CK_RV,
    C_CloseAllSessions: ?*const fn (CK_SLOT_ID) callconv(.c) CK_RV,
    C_GetSessionInfo: ?*const fn (CK_SESSION_HANDLE, *CK_SESSION_INFO) callconv(.c) CK_RV,
    C_GetOperationState: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_SetOperationState: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_OBJECT_HANDLE, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_Login: ?*const fn (CK_SESSION_HANDLE, CK_USER_TYPE, CK_UTF8CHAR_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_Logout: ?*const fn (CK_SESSION_HANDLE) callconv(.c) CK_RV,

    // Object management
    C_CreateObject: ?*const fn (CK_SESSION_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_CopyObject: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_DestroyObject: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_GetObjectSize: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE, *CK_ULONG) callconv(.c) CK_RV,
    C_GetAttributeValue: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG) callconv(.c) CK_RV,
    C_SetAttributeValue: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG) callconv(.c) CK_RV,
    C_FindObjectsInit: ?*const fn (CK_SESSION_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG) callconv(.c) CK_RV,
    C_FindObjects: ?*const fn (CK_SESSION_HANDLE, ?[*]CK_OBJECT_HANDLE, CK_ULONG, *CK_ULONG) callconv(.c) CK_RV,
    C_FindObjectsFinal: ?*const fn (CK_SESSION_HANDLE) callconv(.c) CK_RV,

    // Encryption
    C_EncryptInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_Encrypt: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_EncryptUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_EncryptFinal: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Decryption
    C_DecryptInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_Decrypt: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_DecryptUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_DecryptFinal: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Digesting
    C_DigestInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM) callconv(.c) CK_RV,
    C_Digest: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_DigestUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_DigestKey: ?*const fn (CK_SESSION_HANDLE, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_DigestFinal: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Signing
    C_SignInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_Sign: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_SignUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_SignFinal: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_SignRecoverInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_SignRecover: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Verification
    C_VerifyInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_Verify: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_VerifyUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_VerifyFinal: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_VerifyRecoverInit: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_VerifyRecover: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Dual-function crypto
    C_DigestEncryptUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_DecryptDigestUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_SignEncryptUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_DecryptVerifyUpdate: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,

    // Key management
    C_GenerateKey: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_GenerateKeyPair: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, ?[*]CK_ATTRIBUTE, CK_ULONG, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_WrapKey: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE, CK_OBJECT_HANDLE, CK_BYTE_PTR, CK_ULONG_PTR) callconv(.c) CK_RV,
    C_UnwrapKey: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE, CK_BYTE_PTR, CK_ULONG, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,
    C_DeriveKey: ?*const fn (CK_SESSION_HANDLE, *CK_MECHANISM, CK_OBJECT_HANDLE, ?[*]CK_ATTRIBUTE, CK_ULONG, *CK_OBJECT_HANDLE) callconv(.c) CK_RV,

    // Random number generation
    C_SeedRandom: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,
    C_GenerateRandom: ?*const fn (CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG) callconv(.c) CK_RV,

    // Parallel function management (legacy)
    C_GetFunctionStatus: ?*const fn (CK_SESSION_HANDLE) callconv(.c) CK_RV,
    C_CancelFunction: ?*const fn (CK_SESSION_HANDLE) callconv(.c) CK_RV,

    // Slot event
    C_WaitForSlotEvent: ?*const fn (CK_FLAGS, *CK_SLOT_ID, CK_VOID_PTR) callconv(.c) CK_RV,
};

// Dynamic loader for PKCS#11 modules.
pub const Library = struct {
    handle: std.DynLib,
    func_list: *CK_FUNCTION_LIST,

    pub fn load(path: []const u8) !Library {
        var lib = try std.DynLib.open(path);
        errdefer lib.close();

        const getFunctionList = lib.lookup(
            *const fn (*?*CK_FUNCTION_LIST) callconv(.c) CK_RV,
            "C_GetFunctionList",
        ) orelse return error.SymbolNotFound;

        var func_list: ?*CK_FUNCTION_LIST = null;
        const rv = getFunctionList(&func_list);
        if (rv != CKR_OK) return error.GetFunctionListFailed;

        return .{
            .handle = lib,
            .func_list = func_list orelse return error.NullFunctionList,
        };
    }

    pub fn close(self: *Library) void {
        self.handle.close();
        self.* = undefined;
    }

    pub fn initialize(self: *const Library, args: ?*CK_C_INITIALIZE_ARGS) !void {
        const f = self.func_list.C_Initialize orelse return error.FunctionNotSupported;
        const rv = f(if (args) |a| @ptrCast(a) else null);
        if (rv != CKR_OK) return error.InitializeFailed;
    }

    pub fn finalize(self: *const Library) !void {
        const f = self.func_list.C_Finalize orelse return error.FunctionNotSupported;
        const rv = f(null);
        if (rv != CKR_OK) return error.FinalizeFailed;
    }

    pub fn getInfo(self: *const Library) !CK_INFO {
        const f = self.func_list.C_GetInfo orelse return error.FunctionNotSupported;
        var info: CK_INFO = undefined;
        const rv = f(&info);
        if (rv != CKR_OK) return error.GetInfoFailed;
        return info;
    }

    pub fn getSlotList(self: *const Library, token_present: bool) ![]CK_SLOT_ID {
        const f = self.func_list.C_GetSlotList orelse return error.FunctionNotSupported;
        const present: CK_BBOOL = if (token_present) CK_TRUE else CK_FALSE;
        var count: CK_ULONG = 0;
        var rv = f(present, null, &count);
        if (rv != CKR_OK) return error.GetSlotListFailed;
        if (count == 0) return &.{};
        const slots = try std.heap.c_allocator.alloc(CK_SLOT_ID, count);
        rv = f(present, slots.ptr, &count);
        if (rv != CKR_OK) {
            std.heap.c_allocator.free(slots);
            return error.GetSlotListFailed;
        }
        return slots[0..count];
    }

    pub fn freeSlotList(_: *const Library, slots: []CK_SLOT_ID) void {
        if (slots.len > 0) std.heap.c_allocator.free(slots);
    }

    pub fn getSlotInfo(self: *const Library, slot_id: CK_SLOT_ID) !CK_SLOT_INFO {
        const f = self.func_list.C_GetSlotInfo orelse return error.FunctionNotSupported;
        var info: CK_SLOT_INFO = undefined;
        const rv = f(slot_id, &info);
        if (rv != CKR_OK) return error.GetSlotInfoFailed;
        return info;
    }

    pub fn getTokenInfo(self: *const Library, slot_id: CK_SLOT_ID) !CK_TOKEN_INFO {
        const f = self.func_list.C_GetTokenInfo orelse return error.FunctionNotSupported;
        var info: CK_TOKEN_INFO = undefined;
        const rv = f(slot_id, &info);
        if (rv != CKR_OK) return error.GetTokenInfoFailed;
        return info;
    }

    pub fn getMechanismList(self: *const Library, slot_id: CK_SLOT_ID) ![]CK_MECHANISM_TYPE {
        const f = self.func_list.C_GetMechanismList orelse return error.FunctionNotSupported;
        var count: CK_ULONG = 0;
        var rv = f(slot_id, null, &count);
        if (rv != CKR_OK) return error.GetMechanismListFailed;
        if (count == 0) return &.{};
        const mechs = try std.heap.c_allocator.alloc(CK_MECHANISM_TYPE, count);
        rv = f(slot_id, mechs.ptr, &count);
        if (rv != CKR_OK) {
            std.heap.c_allocator.free(mechs);
            return error.GetMechanismListFailed;
        }
        return mechs[0..count];
    }

    pub fn freeMechanismList(_: *const Library, mechs: []CK_MECHANISM_TYPE) void {
        if (mechs.len > 0) std.heap.c_allocator.free(mechs);
    }

    pub fn getMechanismInfo(self: *const Library, slot_id: CK_SLOT_ID, mechanism: CK_MECHANISM_TYPE) !CK_MECHANISM_INFO {
        const f = self.func_list.C_GetMechanismInfo orelse return error.FunctionNotSupported;
        var info: CK_MECHANISM_INFO = undefined;
        const rv = f(slot_id, mechanism, &info);
        if (rv != CKR_OK) return error.GetMechanismInfoFailed;
        return info;
    }

    pub fn initToken(self: *const Library, slot_id: CK_SLOT_ID, pin: []const u8, label: *[32]u8) !void {
        const f = self.func_list.C_InitToken orelse return error.FunctionNotSupported;
        const rv = f(slot_id, @constCast(pin.ptr), pin.len, label);
        if (rv != CKR_OK) return error.InitTokenFailed;
    }

    pub fn openSession(self: *const Library, slot_id: CK_SLOT_ID, flags: CK_FLAGS) !Session {
        const f = self.func_list.C_OpenSession orelse return error.FunctionNotSupported;
        var handle: CK_SESSION_HANDLE = undefined;
        const rv = f(slot_id, flags, null, null, &handle);
        if (rv != CKR_OK) return error.OpenSessionFailed;
        return .{ .handle = handle, .lib = self };
    }
};

pub const Session = struct {
    handle: CK_SESSION_HANDLE,
    lib: *const Library,

    pub fn close(self: Session) !void {
        const f = self.lib.func_list.C_CloseSession orelse return error.FunctionNotSupported;
        const rv = f(self.handle);
        if (rv != CKR_OK) return error.CloseSessionFailed;
    }

    pub fn getSessionInfo(self: Session) !CK_SESSION_INFO {
        const f = self.lib.func_list.C_GetSessionInfo orelse return error.FunctionNotSupported;
        var info: CK_SESSION_INFO = undefined;
        const rv = f(self.handle, &info);
        if (rv != CKR_OK) return error.GetSessionInfoFailed;
        return info;
    }

    pub fn initPIN(self: Session, pin: []const u8) !void {
        const f = self.lib.func_list.C_InitPIN orelse return error.FunctionNotSupported;
        const rv = f(self.handle, @constCast(pin.ptr), pin.len);
        if (rv != CKR_OK) return error.InitPINFailed;
    }

    pub fn login(self: Session, user_type: CK_USER_TYPE, pin: ?[]const u8) !void {
        const f = self.lib.func_list.C_Login orelse return error.FunctionNotSupported;
        const pin_ptr: CK_UTF8CHAR_PTR = if (pin) |p| @constCast(p.ptr) else null;
        const pin_len: CK_ULONG = if (pin) |p| p.len else 0;
        const rv = f(self.handle, user_type, pin_ptr, pin_len);
        if (rv != CKR_OK) return error.LoginFailed;
    }

    pub fn logout(self: Session) !void {
        const f = self.lib.func_list.C_Logout orelse return error.FunctionNotSupported;
        const rv = f(self.handle);
        if (rv != CKR_OK) return error.LogoutFailed;
    }

    pub fn findObjectsInit(self: Session, template: []CK_ATTRIBUTE) !void {
        const f = self.lib.func_list.C_FindObjectsInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, template.ptr, template.len);
        if (rv != CKR_OK) return error.FindObjectsInitFailed;
    }

    pub fn findObjects(self: Session, out: []CK_OBJECT_HANDLE) ![]CK_OBJECT_HANDLE {
        const f = self.lib.func_list.C_FindObjects orelse return error.FunctionNotSupported;
        var count: CK_ULONG = 0;
        const rv = f(self.handle, out.ptr, out.len, &count);
        if (rv != CKR_OK) return error.FindObjectsFailed;
        return out[0..count];
    }

    pub fn findObjectsFinal(self: Session) !void {
        const f = self.lib.func_list.C_FindObjectsFinal orelse return error.FunctionNotSupported;
        const rv = f(self.handle);
        if (rv != CKR_OK) return error.FindObjectsFinalFailed;
    }

    pub fn getAttributeValue(self: Session, object: CK_OBJECT_HANDLE, template: []CK_ATTRIBUTE) !void {
        const f = self.lib.func_list.C_GetAttributeValue orelse return error.FunctionNotSupported;
        const rv = f(self.handle, object, template.ptr, template.len);
        if (rv != CKR_OK and rv != CKR_ATTRIBUTE_SENSITIVE and rv != CKR_ATTRIBUTE_TYPE_INVALID)
            return error.GetAttributeValueFailed;
    }

    pub fn signInit(self: Session, mechanism: *CK_MECHANISM, key: CK_OBJECT_HANDLE) !void {
        const f = self.lib.func_list.C_SignInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, mechanism, key);
        if (rv != CKR_OK) return error.SignInitFailed;
    }

    pub fn sign(self: Session, data: []const u8, sig_buf: []u8) ![]u8 {
        const f = self.lib.func_list.C_Sign orelse return error.FunctionNotSupported;
        var sig_len: CK_ULONG = sig_buf.len;
        const rv = f(self.handle, @constCast(data.ptr), data.len, sig_buf.ptr, &sig_len);
        if (rv != CKR_OK) return error.SignFailed;
        return sig_buf[0..sig_len];
    }

    pub fn verifyInit(self: Session, mechanism: *CK_MECHANISM, key: CK_OBJECT_HANDLE) !void {
        const f = self.lib.func_list.C_VerifyInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, mechanism, key);
        if (rv != CKR_OK) return error.VerifyInitFailed;
    }

    pub fn verify(self: Session, data: []const u8, signature: []const u8) !void {
        const f = self.lib.func_list.C_Verify orelse return error.FunctionNotSupported;
        const rv = f(self.handle, @constCast(data.ptr), data.len, @constCast(signature.ptr), signature.len);
        if (rv != CKR_OK) return error.VerifyFailed;
    }

    pub fn generateKeyPair(
        self: Session,
        mechanism: *CK_MECHANISM,
        pub_template: []CK_ATTRIBUTE,
        priv_template: []CK_ATTRIBUTE,
    ) !struct { public_key: CK_OBJECT_HANDLE, private_key: CK_OBJECT_HANDLE } {
        const f = self.lib.func_list.C_GenerateKeyPair orelse return error.FunctionNotSupported;
        var pub_key: CK_OBJECT_HANDLE = undefined;
        var priv_key: CK_OBJECT_HANDLE = undefined;
        const rv = f(
            self.handle,
            mechanism,
            pub_template.ptr,
            pub_template.len,
            priv_template.ptr,
            priv_template.len,
            &pub_key,
            &priv_key,
        );
        if (rv != CKR_OK) return error.GenerateKeyPairFailed;
        return .{ .public_key = pub_key, .private_key = priv_key };
    }

    pub fn generateKey(
        self: Session,
        mechanism: *CK_MECHANISM,
        template: []CK_ATTRIBUTE,
    ) !CK_OBJECT_HANDLE {
        const f = self.lib.func_list.C_GenerateKey orelse return error.FunctionNotSupported;
        var key: CK_OBJECT_HANDLE = undefined;
        const rv = f(self.handle, mechanism, template.ptr, template.len, &key);
        if (rv != CKR_OK) return error.GenerateKeyFailed;
        return key;
    }

    pub fn encryptInit(self: Session, mechanism: *CK_MECHANISM, key: CK_OBJECT_HANDLE) !void {
        const f = self.lib.func_list.C_EncryptInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, mechanism, key);
        if (rv != CKR_OK) return error.EncryptInitFailed;
    }

    pub fn encrypt(self: Session, data: []const u8, out_buf: []u8) ![]u8 {
        const f = self.lib.func_list.C_Encrypt orelse return error.FunctionNotSupported;
        var out_len: CK_ULONG = out_buf.len;
        const rv = f(self.handle, @constCast(data.ptr), data.len, out_buf.ptr, &out_len);
        if (rv != CKR_OK) return error.EncryptFailed;
        return out_buf[0..out_len];
    }

    pub fn decryptInit(self: Session, mechanism: *CK_MECHANISM, key: CK_OBJECT_HANDLE) !void {
        const f = self.lib.func_list.C_DecryptInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, mechanism, key);
        if (rv != CKR_OK) return error.DecryptInitFailed;
    }

    pub fn decrypt(self: Session, data: []const u8, out_buf: []u8) ![]u8 {
        const f = self.lib.func_list.C_Decrypt orelse return error.FunctionNotSupported;
        var out_len: CK_ULONG = out_buf.len;
        const rv = f(self.handle, @constCast(data.ptr), data.len, out_buf.ptr, &out_len);
        if (rv != CKR_OK) return error.DecryptFailed;
        return out_buf[0..out_len];
    }

    pub fn destroyObject(self: Session, object: CK_OBJECT_HANDLE) !void {
        const f = self.lib.func_list.C_DestroyObject orelse return error.FunctionNotSupported;
        const rv = f(self.handle, object);
        if (rv != CKR_OK) return error.DestroyObjectFailed;
    }

    pub fn generateRandom(self: Session, buf: []u8) !void {
        const f = self.lib.func_list.C_GenerateRandom orelse return error.FunctionNotSupported;
        const rv = f(self.handle, buf.ptr, buf.len);
        if (rv != CKR_OK) return error.GenerateRandomFailed;
    }

    pub fn digestInit(self: Session, mechanism: *CK_MECHANISM) !void {
        const f = self.lib.func_list.C_DigestInit orelse return error.FunctionNotSupported;
        const rv = f(self.handle, mechanism);
        if (rv != CKR_OK) return error.DigestInitFailed;
    }

    pub fn digest(self: Session, data: []const u8, out_buf: []u8) ![]u8 {
        const f = self.lib.func_list.C_Digest orelse return error.FunctionNotSupported;
        var out_len: CK_ULONG = out_buf.len;
        const rv = f(self.handle, @constCast(data.ptr), data.len, out_buf.ptr, &out_len);
        if (rv != CKR_OK) return error.DigestFailed;
        return out_buf[0..out_len];
    }
};

fn loadSoftHSM2() !Library {
    if (comptime @import("builtin").os.tag == .windows) return error.SkipZigTest;
    const path = std.posix.getenv("SOFTHSM2_PATH") orelse
        return error.SkipZigTest;
    return Library.load(path);
}

fn initTestToken(lib: *const Library) !struct { slot: CK_SLOT_ID, session: Session } {
    const so_pin = "12345678";
    const user_pin = "1234";

    const slots = try lib.getSlotList(false);
    defer lib.freeSlotList(slots);
    if (slots.len == 0) return error.SkipZigTest;

    const slot = slots[0];
    var label: [32]u8 = undefined;
    @memset(&label, ' ');
    @memcpy(label[0..4], "test");
    try lib.initToken(slot, so_pin, &label);

    const session = try lib.openSession(slot, CKF_SERIAL_SESSION | CKF_RW_SESSION);
    errdefer session.close() catch {};

    try session.login(CKU_SO, so_pin);
    try session.initPIN(user_pin);
    try session.logout();

    try session.login(CKU_USER, user_pin);

    return .{ .slot = slot, .session = session };
}

test "load SoftHSM2, initialize, getInfo, finalize" {
    var lib = try loadSoftHSM2();
    defer lib.close();

    try lib.initialize(null);
    defer lib.finalize() catch {};

    const info = try lib.getInfo();
    try std.testing.expect(info.cryptokiVersion.major >= 2);

    const mfr = std.mem.trimRight(u8, &info.manufacturerID, " ");
    try std.testing.expect(std.mem.indexOf(u8, mfr, "SoftHSM") != null);
}

test "SoftHSM2: init token, open session, login" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    const info = try t.session.getSessionInfo();
    try std.testing.expectEqual(CKS_RW_USER_FUNCTIONS, info.state);
}

test "SoftHSM2: slot and token info" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    const slot_info = try lib.getSlotInfo(t.slot);
    try std.testing.expect(slot_info.flags & CKF_TOKEN_PRESENT != 0);

    const token_info = try lib.getTokenInfo(t.slot);
    try std.testing.expect(token_info.flags & CKF_TOKEN_INITIALIZED != 0);
    try std.testing.expect(token_info.flags & CKF_USER_PIN_INITIALIZED != 0);
}

test "SoftHSM2: mechanism list and info" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const slots = try lib.getSlotList(false);
    defer lib.freeSlotList(slots);
    if (slots.len == 0) return error.SkipZigTest;

    const mechs = try lib.getMechanismList(slots[0]);
    defer lib.freeMechanismList(mechs);
    try std.testing.expect(mechs.len > 0);

    // RSA key pair generation should be supported.
    var found_rsa = false;
    for (mechs) |m| {
        if (m == CKM_RSA_PKCS_KEY_PAIR_GEN) {
            found_rsa = true;
            break;
        }
    }
    try std.testing.expect(found_rsa);

    const info = try lib.getMechanismInfo(slots[0], CKM_RSA_PKCS_KEY_PAIR_GEN);
    try std.testing.expect(info.flags & CKF_GENERATE_KEY_PAIR != 0);
}

test "SoftHSM2: generate random" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    var buf: [32]u8 = undefined;
    @memset(&buf, 0);
    try t.session.generateRandom(&buf);

    // Extremely unlikely to be all zeros after filling with random.
    var all_zero = true;
    for (buf) |b| {
        if (b != 0) {
            all_zero = false;
            break;
        }
    }
    try std.testing.expect(!all_zero);
}

test "SoftHSM2: RSA key pair generation, sign, verify" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    var modulus_bits: CK_ULONG = 2048;
    const pub_exp = [_]u8{ 0x01, 0x00, 0x01 }; // 65537
    var pub_class = CKO_PUBLIC_KEY;
    var priv_class = CKO_PRIVATE_KEY;
    var key_type = CKK_RSA;
    var ck_true = CK_TRUE;

    var pub_template = [_]CK_ATTRIBUTE{
        .{ .type = CKA_CLASS, .pValue = @ptrCast(&pub_class), .ulValueLen = @sizeOf(CK_OBJECT_CLASS) },
        .{ .type = CKA_KEY_TYPE, .pValue = @ptrCast(&key_type), .ulValueLen = @sizeOf(CK_KEY_TYPE) },
        .{ .type = CKA_MODULUS_BITS, .pValue = @ptrCast(&modulus_bits), .ulValueLen = @sizeOf(CK_ULONG) },
        .{ .type = CKA_PUBLIC_EXPONENT, .pValue = @ptrCast(@constCast(&pub_exp)), .ulValueLen = pub_exp.len },
        .{ .type = CKA_VERIFY, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
        .{ .type = CKA_TOKEN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
    };
    var priv_template = [_]CK_ATTRIBUTE{
        .{ .type = CKA_CLASS, .pValue = @ptrCast(&priv_class), .ulValueLen = @sizeOf(CK_OBJECT_CLASS) },
        .{ .type = CKA_KEY_TYPE, .pValue = @ptrCast(&key_type), .ulValueLen = @sizeOf(CK_KEY_TYPE) },
        .{ .type = CKA_SIGN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
        .{ .type = CKA_TOKEN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
    };

    var mech = CK_MECHANISM{ .mechanism = CKM_RSA_PKCS_KEY_PAIR_GEN, .pParameter = null, .ulParameterLen = 0 };
    const keys = try t.session.generateKeyPair(&mech, &pub_template, &priv_template);

    // Sign with RSA-PKCS#1.
    const message = "test message for signing";
    var sign_mech = CK_MECHANISM{ .mechanism = CKM_RSA_PKCS, .pParameter = null, .ulParameterLen = 0 };
    try t.session.signInit(&sign_mech, keys.private_key);
    var sig_buf: [256]u8 = undefined;
    const signature = try t.session.sign(message, &sig_buf);
    try std.testing.expect(signature.len > 0);

    // Verify.
    try t.session.verifyInit(&sign_mech, keys.public_key);
    try t.session.verify(message, signature);

    // Cleanup.
    try t.session.destroyObject(keys.public_key);
    try t.session.destroyObject(keys.private_key);
}

test "SoftHSM2: find objects" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    // Generate a key so there's something to find.
    var modulus_bits: CK_ULONG = 2048;
    const pub_exp = [_]u8{ 0x01, 0x00, 0x01 };
    var ck_true = CK_TRUE;
    var pub_class = CKO_PUBLIC_KEY;
    var priv_class = CKO_PRIVATE_KEY;
    var key_type = CKK_RSA;

    var pub_template = [_]CK_ATTRIBUTE{
        .{ .type = CKA_CLASS, .pValue = @ptrCast(&pub_class), .ulValueLen = @sizeOf(CK_OBJECT_CLASS) },
        .{ .type = CKA_KEY_TYPE, .pValue = @ptrCast(&key_type), .ulValueLen = @sizeOf(CK_KEY_TYPE) },
        .{ .type = CKA_MODULUS_BITS, .pValue = @ptrCast(&modulus_bits), .ulValueLen = @sizeOf(CK_ULONG) },
        .{ .type = CKA_PUBLIC_EXPONENT, .pValue = @ptrCast(@constCast(&pub_exp)), .ulValueLen = pub_exp.len },
        .{ .type = CKA_VERIFY, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
        .{ .type = CKA_TOKEN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
    };
    var priv_template = [_]CK_ATTRIBUTE{
        .{ .type = CKA_CLASS, .pValue = @ptrCast(&priv_class), .ulValueLen = @sizeOf(CK_OBJECT_CLASS) },
        .{ .type = CKA_KEY_TYPE, .pValue = @ptrCast(&key_type), .ulValueLen = @sizeOf(CK_KEY_TYPE) },
        .{ .type = CKA_SIGN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
        .{ .type = CKA_TOKEN, .pValue = @ptrCast(&ck_true), .ulValueLen = @sizeOf(CK_BBOOL) },
    };

    var mech = CK_MECHANISM{ .mechanism = CKM_RSA_PKCS_KEY_PAIR_GEN, .pParameter = null, .ulParameterLen = 0 };
    const keys = try t.session.generateKeyPair(&mech, &pub_template, &priv_template);

    // Find all public keys.
    var find_class = CKO_PUBLIC_KEY;
    var find_template = [_]CK_ATTRIBUTE{
        .{ .type = CKA_CLASS, .pValue = @ptrCast(&find_class), .ulValueLen = @sizeOf(CK_OBJECT_CLASS) },
    };
    try t.session.findObjectsInit(&find_template);
    var handles: [16]CK_OBJECT_HANDLE = undefined;
    const found = try t.session.findObjects(&handles);
    try t.session.findObjectsFinal();

    try std.testing.expect(found.len >= 1);

    // Cleanup.
    try t.session.destroyObject(keys.public_key);
    try t.session.destroyObject(keys.private_key);
}

test "SoftHSM2: digest SHA-256" {
    var lib = try loadSoftHSM2();
    defer lib.close();
    try lib.initialize(null);
    defer lib.finalize() catch {};

    const t = try initTestToken(&lib);
    defer t.session.close() catch {};
    defer t.session.logout() catch {};

    var mech = CK_MECHANISM{ .mechanism = CKM_SHA256, .pParameter = null, .ulParameterLen = 0 };
    try t.session.digestInit(&mech);

    const data = "hello world";
    var hash_buf: [32]u8 = undefined;
    const hash = try t.session.digest(data, &hash_buf);
    try std.testing.expectEqual(@as(usize, 32), hash.len);

    // Known SHA-256 of "hello world".
    const expected = [_]u8{
        0xb9, 0x4d, 0x27, 0xb9, 0x93, 0x4d, 0x3e, 0x08,
        0xa5, 0x2e, 0x52, 0xd7, 0xda, 0x7d, 0xab, 0xfa,
        0xc4, 0x84, 0xef, 0xe3, 0x7a, 0x53, 0x80, 0xee,
        0x90, 0x88, 0xf7, 0xac, 0xe2, 0xef, 0xcd, 0xe9,
    };
    try std.testing.expectEqualSlices(u8, &expected, hash);
}
